<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 3                     */
/* CACHE FILE: Generated: Wed, 02 Jun 2010 18:46:25 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_editors_3 {

 var $ipsclass;
//===========================================================================
// <ips:editor_rte:desc::trigger:>
//===========================================================================
function editor_rte($text="",$form_field='post_content',$width="",$height="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<!-- RTE -->
<input type='hidden' name='rte_used' value='1' />
<script type=\"text/javascript\" src=\"jscripts/ipb_editor.js\"></script>
<script language=\"JavaScript\" type=\"text/javascript\" src=\"jscripts/ipb_editor_rte.js\"></script>
<script language=\"JavaScript\" type=\"text/javascript\" src=\"{ipb.vars['img_url']}/folder_rte_files/rte_html.js\"></script>
<script language=\"JavaScript\" type=\"text/javascript\">
//<![CDATA[
// INIT
var postformid;
var postfieldid;
var postformobj;
var postfieldobj;
var MessageMax          = parseInt(\"{ipb.lang['the_max_length']}\");
var Override            = \"{ipb.lang['override']}\";
// Charset
var g_CHARSET           = \"{ipb.vars['gb_char_set']}\";
// Tooltips
var js_tt_bold          = \"{ipb.lang['js_tt_bold']}\";
var js_tt_italic        = \"{ipb.lang['js_tt_italic']}\";
var js_tt_underline     = \"{ipb.lang['js_tt_underline']}\";
var js_tt_strike        = \"{ipb.lang['js_tt_strike']}\";
var js_tt_font_col      = \"{ipb.lang['js_tt_font_col']}\";
var js_tt_back_col      = \"{ipb.lang['js_tt_back_col']}\";
var js_tt_link          = \"{ipb.lang['js_tt_link']}\";
var js_tt_image         = \"{ipb.lang['js_tt_image']}\";
var js_tt_email         = \"{ipb.lang['js_tt_email']}\";
var js_tt_quote         = \"{ipb.lang['js_tt_quote']}\";
var js_tt_left          = \"{ipb.lang['js_tt_left']}\";
var js_tt_center        = \"{ipb.lang['js_tt_center']}\";
var js_tt_right         = \"{ipb.lang['js_tt_right']}\";
var js_tt_list          = \"{ipb.lang['js_tt_list']}\";
var js_tt_indent        = \"{ipb.lang['js_tt_indent']}\";
var js_tt_outdent       = \"{ipb.lang['js_tt_outdent']}\";
var js_tt_noformat      = \"{ipb.lang['js_tt_noformat']}\";
var js_tt_undo          = \"{ipb.lang['js_tt_undo']}\";
var js_tt_redo          = \"{ipb.lang['js_tt_redo']}\";
var js_tt_copy          = \"{ipb.lang['js_tt_copy']}\";
var js_tt_paste         = \"{ipb.lang['js_tt_paste']}\";
var js_tt_cut           = \"{ipb.lang['js_tt_cut']}\";
var js_tt_code          = \"{ipb.lang['js_tt_code']}\";
// Validate Form text
var js_used             = \"{ipb.lang['js_used']}\";
var js_max_length       = \"{ipb.lang['js_max_length']}\";
var js_post             = \"{ipb.lang['js_post']}\";
var js_no_message       = \"{ipb.lang['js_no_message']}\";
var js_current          = \"{ipb.lang['js_current']}\";
var js_characters       = \"{ipb.lang['js_characters']}\";
var js_msg_no_title     = \"{ipb.lang['msg_no_title']}\";
var js_remove_attach    = \"{ipb.lang['remove_attach']}\";
// Extra Lang Bits
var text_enter_url        = \"{ipb.lang['jscode_text_enter_url']}\";
var text_enter_url_name   = \"{ipb.lang['jscode_text_enter_url_name']}\";
var text_enter_image      = \"{ipb.lang['jscode_text_enter_image']}\";
var text_enter_email    = \"{ipb.lang['jscode_text_enter_email']}\";
var jsfile_error_lang     = \"{ipb.lang['jsfile_error']}\";
var jsfile_myweb_lang     = \"{ipb.lang['jsfile_mywebpage']}\";
var jsfile_errorc_lang    = \"{ipb.lang['jsfile_error_c']}\";
var jsfile_alert1         = \"{ipb.lang['jsfile_alert1']}\";
var jsfile_alert2         = \"{ipb.lang['jsfile_alert2']}\";
var jsfile_alert3         = \"{ipb.lang['jsfile_alert3']}\";
var jsfile_alert4         = \"{ipb.lang['jsfile_alert4']}\";
var jsfile_highlight_lang = \"{ipb.lang['jsfile_highlight']}\";
var jsfile_erroriespell   = \"{ipb.lang['jsfile_erroriespell']}\";
var jsfile_errorliespell  = \"{ipb.lang['jsfile_errorliespell']}\";
var is_fs_mode = 0;
init_editor();
init_rte(\"{ipb.vars['img_url']}/folder_rte_images/\", \"{ipb.vars['img_url']}/folder_rte_files/\");
write_rte_editor('{$form_field}', '{$text}', '{$width}', '{$height}', true, false);
//]]>
</script>
<!-- /RTE -->";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:editor_std:desc::trigger:>
//===========================================================================
function editor_std($text="",$form_field='post_content',$width="",$height="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<script type=\"text/javascript\">
//<![CDATA[
// INIT
var postformid;
var postfieldid;
var postformobj;
var postfieldobj;
var MessageMax          = parseInt(\"{ipb.lang['the_max_length']}\");
var Override            = \"{ipb.lang['override']}\";
// Easy prompts
var text_enter_url      = \"{ipb.lang['jscode_text_enter_url']}\";
var text_enter_url_name = \"{ipb.lang['jscode_text_enter_url_name']}\";
var text_enter_image    = \"{ipb.lang['jscode_text_enter_image']}\";
var text_enter_email    = \"{ipb.lang['jscode_text_enter_email']}\";
var text_code           = \"{ipb.lang['jscode_text_code']}\";
var text_quote          = \"{ipb.lang['jscode_text_quote']}\";
var error_no_url        = \"{ipb.lang['jscode_error_no_url']}\";
var error_no_title      = \"{ipb.lang['jscode_error_no_title']}\";
var error_no_email      = \"{ipb.lang['jscode_error_no_email']}\";
var prompt_start        = \"{ipb.lang['js_text_to_format']}\";
var list_prompt         = \"{ipb.lang['js_tag_list']}\";
// Validate Form text
var js_used             = \"{ipb.lang['js_used']}\";
var js_max_length       = \"{ipb.lang['js_max_length']}\";
var js_post             = \"{ipb.lang['js_post']}\";
var js_no_message       = \"{ipb.lang['js_no_message']}\";
var js_current          = \"{ipb.lang['js_current']}\";
var js_characters       = \"{ipb.lang['js_characters']}\";
var js_msg_no_title     = \"{ipb.lang['msg_no_title']}\";
var js_remove_attach    = \"{ipb.lang['remove_attach']}\";
// Easy mode toggle
var js_bbeasy_on        = \"{ipb.lang['js_bbeasy_on']}\";
var js_bbeasy_off       = \"{ipb.lang['js_bbeasy_off']}\";
var js_bbeasy_toggle    = \"{ipb.lang['js_bbeasy_toggle']}\";
var js_check_length     = \"{ipb.lang['js_check_length']}\";
// Extra Lang Bits
var jsfile_error_lang   = \"{ipb.lang['jsfile_error']}\";
var jsfile_myweb_lang = \"{ipb.lang['jsfile_mywebpage']}\";
//]]>
</script>
<script type=\"text/javascript\" src=\"jscripts/ipb_editor.js\"></script>
<script type=\"text/javascript\" src=\"jscripts/ipb_editor_std.js\"></script>
" . ((ipb.force_editor_change == 1) ? ("
<div class='borderwrap'>
 <div class='row1' style='padding:4px'>{ipb.lang['js_forced_change']}</div>
</div>
") : ("")) . "

  <!-- START NORMAL POST BUTTONS -->
  <div class=\"rteDiv\" style=\"width:{$width}\" align='left'>
    <!-- Color palette -->
	<iframe width=\"154\" height=\"104\" id=\"cp\" src=\"{ipb.vars['img_url']}/folder_rte_files/palette.html\" marginwidth=\"0\" marginheight=\"0\" scrolling=\"no\" style=\"visibility:hidden; display: none; position: absolute;\"></iframe>
	<!-- /Color palette -->
   <!-- Row 1 -->
   <table class=\"rtebuttonbar1\" cellpadding=\"2\" cellspacing=\"0\" id=\"Buttons1\">
	<tr>
	<td width='1%' align='left' nowrap='nowrap'>
	  <table cellpadding='0' cellspacing='0' width='100%'>
	   <tr>
	    <td><img class=\"rteVertSep\" src=\"{ipb.vars['img_url']}/folder_rte_images/rte_dots.gif\" width=\"3\" height=\"15\" border=\"0\" alt=\"\"></td>
	    <td><select name=\"ffont\" class=\"codebuttons\" onchange=\"alterfont(this.options[this.selectedIndex].value, 'font')\">
	            <option value='0'>{ipb.lang['box_font']}</option>
				<script type=\"text/javascript\">document.write( write_fontface_box() );</script>
			</select></td>
	     <td><select name=\"fsize\" class=\"codebuttons\" onchange=\"alterfont(this.options[this.selectedIndex].value, 'size')\">
				<option value='0'>{ipb.lang['box_size']}</option>
				<script type=\"text/javascript\">document.write( write_fontsize_box() );</script>
			</select></td>
		 <!--SEP-->
	     <td><img class=\"rteVertSep\" src=\"{ipb.vars['img_url']}/folder_rte_images/blackdot.gif\" width=\"1\" height=\"20\" border=\"0\" alt=\"\"></td>
	     <!--/SEP-->
	     <td><div id=\"do_indent\"><img class=\"rteimage\" src=\"{ipb.vars['img_url']}/folder_rte_images/indent.gif\" width=\"25\" height=\"24\" alt=\"{ipb.lang['js_tt_indent']}\" title=\"{ipb.lang['js_tt_indent']}\" onclick=\"simpletag('indent')\"></div></td>
	    </tr>
	    </table>
	</td>
	 <td width='98%'>&nbsp;</td>
	 <td width='1%' nowrap='nowrap' align='right'>
	  <table cellpadding='0' cellspacing='0' width='100%'>
	   <tr>
	    <td><div id=\"do_closeall\"><img class=\"rteimage\" src=\"{ipb.vars['img_url']}/folder_rte_images/closeall.gif\" width=\"25\" height=\"24\" alt=\"{ipb.lang['js_tt_closeall']}\" title=\"{ipb.lang['js_tt_closeall']}\" onclick=\"closeall()\"></div></td>
	   </tr>
	  </table>
	 </td>
	</tr>
	</table>
   <!-- /Row 1 -->
   <!-- Row 2 -->
   <table class=\"rtebuttonbar1\" cellpadding=\"2\" cellspacing=\"0\" id=\"Buttons1\">
	<tr>
	<td width='1%' align='left' nowrap='nowrap'>
	  <table cellpadding='0' cellspacing='0' width='100%'>
	   <tr>
	    <td><img class=\"rteVertSep\" src=\"{ipb.vars['img_url']}/folder_rte_images/rte_dots.gif\" width=\"3\" height=\"15\" border=\"0\" alt=\"\"></td>
	    
	    <td><div id=\"do_bold\"><img class=\"rteimage\" src=\"{ipb.vars['img_url']}/folder_rte_images/bold.gif\" width=\"25\" height=\"24\" alt=\"{ipb.lang['js_tt_bold']}\" title=\"{ipb.lang['js_tt_bold']}\" onclick=\"simpletag('b')\"></div></td>
	    <td><div id=\"do_italic\"><img class=\"rteimage\" src=\"{ipb.vars['img_url']}/folder_rte_images/italic.gif\" width=\"25\" height=\"24\" alt=\"{ipb.lang['js_tt_italic']}\" title=\"{ipb.lang['js_tt_italic']}\" onclick=\"simpletag('i')\"></div></td>
	    <td><div id=\"do_underline\"><img class=\"rteimage\" src=\"{ipb.vars['img_url']}/folder_rte_images/underline.gif\" width=\"25\" height=\"24\" alt=\"{ipb.lang['js_tt_underline']}\" title=\"{ipb.lang['js_tt_underline']}\" onclick=\"simpletag('u')\"></div></td>
	    <td><div id=\"do_strikethrough\"><img class=\"rteimage\" src=\"{ipb.vars['img_url']}/folder_rte_images/strike.gif\" width=\"25\" height=\"24\" alt=\"{ipb.lang['js_tt_strike']}\" title=\"{ipb.lang['js_tt_strike']}\" onclick=\"simpletag('s')\"></div></td>
	    <!--SEP-->
	    <td><img class=\"rteVertSep\" src=\"{ipb.vars['img_url']}/folder_rte_images/blackdot.gif\" width=\"1\" height=\"20\" border=\"0\" alt=\"\"></td>
	    <!--/SEP-->
	    <td><div id=\"forecolor\"><img class=\"rteimage\" src=\"{ipb.vars['img_url']}/folder_rte_images/textcolor.gif\" width=\"25\" height=\"24\" alt=\"{ipb.lang['js_tt_font_col']}\" title=\"{ipb.lang['js_tt_font_col']}\" onclick=\"popcolor('forecolor');\"></div></td>
	    <td><div id=\"hilitecolor\"><img class=\"rteimage\" src=\"{ipb.vars['img_url']}/folder_rte_images/bgcolor.gif\" width=\"25\" height=\"24\" alt=\"{ipb.lang['js_tt_back_col']}\" title=\"{ipb.lang['js_tt_back_col']}\" onclick=\"popcolor('hilitecolor');\"></div></td>
	    <!--SEP-->
	    <td><img class=\"rteVertSep\" src=\"{ipb.vars['img_url']}/folder_rte_images/blackdot.gif\" width=\"1\" height=\"20\" border=\"0\" alt=\"\"></td>
	    <!--/SEP-->
	    <td><div><img class=\"rteimage\" src=\"{ipb.vars['img_url']}/folder_rte_images/hyperlink.gif\" width=\"25\" height=\"24\" alt=\"{ipb.lang['js_tt_link']}\" title=\"{ipb.lang['js_tt_link']}\" onclick=\"tag_url()\"></div></td>
	    <td><div><img class=\"rteimage\" src=\"{ipb.vars['img_url']}/folder_rte_images/email.gif\" width=\"25\" height=\"24\" alt=\"{ipb.lang['js_tt_email']}\" title=\"{ipb.lang['js_tt_email']}\" onclick=\"tag_email()\"></div></td>
	    <td><div><img class=\"rteimage\" src=\"{ipb.vars['img_url']}/folder_rte_images/image.gif\" width=\"25\" height=\"24\" alt=\"{ipb.lang['js_tt_image']}\" title=\"{ipb.lang['js_tt_image']}\" onclick=\"tag_image()\"></div></td>
	    <!--SEP-->
	    <td><img class=\"rteVertSep\" src=\"{ipb.vars['img_url']}/folder_rte_images/blackdot.gif\" width=\"1\" height=\"20\" border=\"0\" alt=\"\"></td>
	    <!--/SEP-->
	     <td><div id='do_quote'><img class=\"rteimage\" src=\"{ipb.vars['img_url']}/folder_rte_images/quote.gif\" width=\"21\" height=\"21\" alt=\"{ipb.lang['js_tt_quote']}\" title=\"{ipb.lang['js_tt_quote']}\" onclick=\"simpletag('quote')\"></div></td>
	     <td><div id='do_code'><img class=\"rteimage\" src=\"{ipb.vars['img_url']}/folder_rte_images/code.gif\" width=\"21\" height=\"21 alt=\"{ipb.lang['js_tt_code']}\" title=\"{ipb.lang['js_tt_code']}\" onclick=\"simpletag('code')\"></div></td>
	   </tr>
	   </table>
	</td>
	 <td width='98%'>&nbsp;</td>
	 <td width='1%' nowrap='nowrap' align='right'>
	  <table cellpadding='0' cellspacing='0' width='100%'>
	   <tr>
	    <td><div id=\"do_justifyleft\"><img class=\"rteimage\" src=\"{ipb.vars['img_url']}/folder_rte_images/left_just.gif\" width=\"25\" height=\"24\" alt=\"{ipb.lang['js_tt_left']}\" title=\"{ipb.lang['js_tt_left']}\" onClick=\"simpletag('left')\"></div></td>
	    <td><div id=\"do_justifycenter\"><img class=\"rteimage\" src=\"{ipb.vars['img_url']}/folder_rte_images/centre.gif\" width=\"25\" height=\"24\" alt=\"{ipb.lang['js_tt_center']}\" title=\"{ipb.lang['js_tt_center']}\" onClick=\"simpletag('center')\"></div></td>
	    <td><div id=\"do_justifyright\"><img class=\"rteimage\" src=\"{ipb.vars['img_url']}/folder_rte_images/right_just.gif\" width=\"25\" height=\"24\" alt=\"{ipb.lang['js_tt_right']}\" title=\"{ipb.lang['js_tt_right']}\" onClick=\"simpletag('right')\"></div></td>
		<!--SEP-->
	    <td><img class=\"rteVertSep\" src=\"{ipb.vars['img_url']}/folder_rte_images/blackdot.gif\" width=\"1\" height=\"20\" border=\"0\" alt=\"\"></td>
	    <!--/SEP-->
	    <td><div><img class=\"rteimage\" src=\"{ipb.vars['img_url']}/folder_rte_images/numbered_list.gif\" width=\"25\" height=\"24\" alt=\"{ipb.lang['js_tt_list']}\" title=\"{ipb.lang['js_tt_list']}\" onClick=\"tag_list('ordered')\"></div></td>
	    <td><div><img class=\"rteimage\" src=\"{ipb.vars['img_url']}/folder_rte_images/list.gif\" width=\"25\" height=\"24\" alt=\"{ipb.lang['js_tt_list']}\" title=\"{ipb.lang['js_tt_list']}\" onClick=\"tag_list('unordered')\"></div></td>
	   </tr>
	  </table>
	 </td>
	</tr>
	</table>
   <!-- /Row 2 -->
   <!-- END NORMAL POST BUTTONS -->
 </div>
  <textarea cols=\"80\" rows=\"20\" style='margin:0px;width:{$width}' id='postcontent' name=\"{$form_field}\" tabindex=\"5\" class=\"rteiframe\">$text</textarea>
 <div class=\"rteDiv\" style=\"width:{$width}\">
   <!-- Bottom Buttons -->
   <table cellpadding=\"0\" cellspacing=\"0\" style=\"padding:0px;margin:0px;\" id='std-table-buttons' width=\"100%\">
	<tr>
	 <td style=\"padding:0px;margin:0px;\" align=\"left\" width=\"1%\" valign='top' nowrap=\"nowrap\">
	  <input type=\"button\" value=\" + \" onclick='std_window_resize( 100  );' id=\"rtesizeplus\"  class=\"rtebottombutton\" />
	  <input type=\"button\" value=\" - \" onclick='std_window_resize( -100 );' id=\"rtesizeminus\" class=\"rtebottombutton\" />
	</td>
	 <td style=\"padding:0px;margin:0px;height:30px\" align=\"right\" valign='top' width=\"99%\">
	  <input type=\"button\" value=\" {ipb.lang['button_init']} \" title='{ipb.lang['js_bbeasy_toggle']}' onclick='toggle_bbmode(); return false;' id=\"togglebbmode\"  class=\"rtebottombutton\" />
	  <input type=\"button\" value=\"{ipb.lang['js_check_length']}\" title='{ipb.lang['js_check_length']}' onclick='check_length(); return false;' id=\"checklength\"  class=\"rtebottombutton\" />
	 </td>
	</tr>
	</table>
	<!-- / Bottom Buttons -->
  </div>
  <!-- Prep BBCode buttons & Editor -->
  <script type=\"text/javascript\">
	  init_editor();
	  init_std_editor();
  </script>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:ips_editor:desc::trigger:>
//===========================================================================
function ips_editor($form_field="",$initial_content="",$images_path="",$inc_path="",$rte_mode=0,$editor_id='ed-0',$smilies='',$bbcode='',$can_use_emos=1) {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<!--top-->
" . (($editor_id == 'ed-0') ? ("
<script type=\"text/javascript\" src=\"jscripts/ips_text_editor.js\"></script>
<script type=\"text/javascript\" src=\"jscripts/ips_text_editor_func.js\"></script>
<style type='text/css'>
@import url( \"{$images_path}css_rte.css\" );
</style>
") : ("")) . "
<input type='hidden' name='{$editor_id}_wysiwyg_used' id='{$editor_id}_wysiwyg_used' value='0' />
<input type='hidden' name='editor_ids[]' value='{$editor_id}' />
<table width='100%'>
 <tr>
  <td nowrap='nowrap' id='{$editor_id}_options-bar' class=\"rte-option-panel\" style='width:0px;'></td>
  <td id='{$editor_id}_spacer-bar' width='4px'>&nbsp;</td>
  <td nowrap='nowrap' style='width:100%;' id='{$editor_id}_main-bar' class=\"rte-buttonbar\" valign='top'>
<!-- Main editor wrapper -->
    <div id='{$editor_id}_controls' style='display:none;padding:6px;text-align:left'>
        <table cellpadding=\"2\" cellspacing=\"0\" width='100%'>
        <tr>
        <td width='1%' align='left' nowrap='nowrap'>
          <table cellpadding='0' cellspacing='0' width='100%'>
           <tr>
            <td><div class='rte-normal' id=\"{$editor_id}_cmd_removeformat\"><img src=\"{$images_path}rte-remove-formatting.gif\" alt=\"{$this->ipsclass->lang['js_tt_noformat']}\" title=\"{$this->ipsclass->lang['js_tt_noformat']}\" ></div></td>
            <td><div class='rte-normal' id=\"{$editor_id}_cmd_togglesource\"><img src=\"{$images_path}rte-toggle-html.gif\" alt=\"{$this->ipsclass->lang['js_tt_htmlsource']}\" title=\"{$this->ipsclass->lang['js_tt_htmlsource']}\" ></div></td>
			<td><img class=\"rteVertSep\" src=\"{$images_path}rte_dots.gif\" width=\"1\" height=\"20\" border=\"0\" alt=\"\"></td> 
			<td>
				<div class='rte-menu-button' id='{$editor_id}_popup_special' title='{$this->ipsclass->lang['js_tt_insert_item']}' style='margin-right:2px;margin-left:2px;width:168px'>
					<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\">
					<tr>
						<td><div id='{$editor_id}_out_special' style='width:150px'>{$this->ipsclass->lang['js_tt_insert_item']}</div></td>
						<td align='right'><img class=\"ipd\" src=\"{$images_path}icon_open.gif\"  border=\"0\" alt=\"\"></td>
					</tr>
					</table>
				</div>
			</td>
			<td>
				<div class='rte-menu-button' id='{$editor_id}_popup_fontname' title='{$this->ipsclass->lang['box_font']}' style='margin-right:2px;width:148px'>
					<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\">
					<tr>
						<td><div id='{$editor_id}_out_fontname' style='width:130px'>&nbsp;</div></td>
						<td align='right'><img class=\"ipd\" src=\"{$images_path}icon_open.gif\"  border=\"0\" alt=\"\"></td>
					</tr>
					</table>
				</div>
			</td>
            <td>
				<div class='rte-menu-button' id='{$editor_id}_popup_fontsize' title='{$this->ipsclass->lang['box_size']}' style='width:78px'>
					<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\">
					<tr>
						<td><div id='{$editor_id}_out_fontsize' style='width:60px'>&nbsp;</div></td>
						<td align='right'><img class=\"ipd\" src=\"{$images_path}icon_open.gif\"  border=\"0\" alt=\"\"></td>
					</tr>
					</table>
				</div>
			</td>
			<td>
				<div class='rte-menu-button' id='{$editor_id}_popup_forecolor' title='{$this->ipsclass->lang['js_tt_font_col']}' style='margin-left:2px;width:41px'>
					<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\">
					<tr>
						<td><div id='{$editor_id}_out_color'>&nbsp;</div></td>
						<td nowrap=\"nowrap\">
							<img class='ipd' src=\"{$images_path}rte-textcolor.gif\" alt=\"{$this->ipsclass->lang['js_tt_font_col']}\" title=\"{$this->ipsclass->lang['js_tt_font_col']}\" >
							<img class=\"ipd\" src=\"{$images_path}icon_open.gif\"  border=\"0\" alt=\"\">
						</td>
					</tr>
					</table>
				</div>
			</td>
           </tr>
          </table>
         </td>
         <td width='98%'>&nbsp;</td>
         <td width='1%' nowrap='nowrap' align='right'>
          <table cellpadding='0' cellspacing='0' width='100%'>
           <tr>
               <td><div class=\"rte-normal\" id=\"{$editor_id}_cmd_spellcheck\"><img src=\"{$images_path}spellcheck.gif\" width=\"25\" height=\"24\" alt=\"{$this->ipsclass->lang['js_tt_spellcheck']}\" title=\"{$this->ipsclass->lang['js_tt_spellcheck']}\" ></div></td>
               <td><div class=\"rte-normal\" id=\"{$editor_id}_cmd_undo\" style='padding:5px'><img src=\"{$images_path}rte-undo.png\" style=\"width:16px;height:16px;\" alt=\"{$this->ipsclass->lang['js_tt_undo']}\" title=\"{$this->ipsclass->lang['js_tt_undo']}\" ></div></td>
               <td><div class=\"rte-normal\" id=\"{$editor_id}_cmd_redo\" style='padding:5px'><img src=\"{$images_path}rte-redo.png\" style=\"width:16px;height:16px;\" alt=\"{$this->ipsclass->lang['js_tt_redo']}\" title=\"{$this->ipsclass->lang['js_tt_redo']}\" ></div></td>
			   <td>
				   <div class=\"rte-normal\" style='padding:0px;margin:0px;' id=\"{$editor_id}_cmd_resize_up\"><img src=\"{$images_path}rte-resize-up.gif\"  alt=\"{$this->ipsclass->lang['js_tt_smaller']}\" title=\"{$this->ipsclass->lang['js_tt_smaller']}\"></div>
				   <div class=\"rte-normal\" style='padding:0px;margin:0px;padding-top:1px' id=\"{$editor_id}_cmd_resize_down\"><img src=\"{$images_path}rte-resize-down.gif\"  alt=\"{$this->ipsclass->lang['js_tt_larger']}\" title=\"{$this->ipsclass->lang['js_tt_larger']}\"></div>
			   </td>
			   " . (($this->ipsclass->vars['posting_allow_rte'] == 1) ? ("
			   	<td><div class=\"rte-normal\" id=\"{$editor_id}_cmd_switcheditor\"><img src=\"{$images_path}rte-switch-editor.png\" alt=\"{$this->ipsclass->lang['js_tt_switcheditor']}\" title=\"{$this->ipsclass->lang['js_tt_switcheditor']}\" ></div></td>
			   ") : ("")) . "
           </tr>
          </table>
         </td>
        </tr>
        </table>
        <table cellpadding=\"2\" cellspacing=\"0\" id=\"Buttons2\" width='100%'>
        <tr>
         <td width='1%' align='left' nowrap='nowrap'>
          <table cellpadding='0' cellspacing='0' width='100%'>
           <tr>
             <td><div class=\"rte-normal\" id=\"{$editor_id}_cmd_bold\"><img src=\"{$images_path}rte-bold.png\"  alt=\"{$this->ipsclass->lang['js_tt_bold']}\" title=\"{$this->ipsclass->lang['js_tt_bold']}\"></div></td>
             <td><div class=\"rte-normal\" id=\"{$editor_id}_cmd_italic\"><img src=\"{$images_path}rte-italic.png\"  alt=\"{$this->ipsclass->lang['js_tt_italic']}\" title=\"{$this->ipsclass->lang['js_tt_italic']}\" ></div></td>
             <td><div class=\"rte-normal\" id=\"{$editor_id}_cmd_underline\"><img src=\"{$images_path}rte-underlined.png\" alt=\"{$this->ipsclass->lang['js_tt_underline']}\" title=\"{$this->ipsclass->lang['js_tt_underline']}\" ></div></td>
			 <td>
             	<div class='rte-menu-button' id='{$editor_id}_popup_format' title='{$this->ipsclass->lang['js_text_formatting']}' style='margin-right:4px;margin-left:3px;width:41px'>
					<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\">
					<tr>
						<td><div id='{$editor_id}_out_format'>&nbsp;</div></td>
						<td nowrap=\"nowrap\"><img class=\"ipd\" src=\"{$images_path}rte-extra.png\" alt=\"{$this->ipsclass->lang['js_extra_formatting']}\" title=\"{$this->ipsclass->lang['js_extra_formatting']}\" >
							 <img class=\"ipd\" src=\"{$images_path}icon_open.gif\"  border=\"0\" alt=\"\">
						</td>
					</tr>
					</table>
				</div>
			 </td>
             <td>
				<div class='rte-menu-button' id='{$editor_id}_popup_backcolor' title='{$this->ipsclass->lang['js_tt_back_col']}' style='margin-right:4px;width:41px;display:none'>
					<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\">
					<tr>
						<td><div id='{$editor_id}_out_bgcolor'>&nbsp;</div></td>
						<td nowrap=\"nowrap\">
							<img class='ipd' src=\"{$images_path}rte-bgcolor.gif\" alt=\"{$this->ipsclass->lang['js_tt_font_col']}\" title=\"{$this->ipsclass->lang['js_tt_back_col']}\" >
							<img class=\"ipd\" src=\"{$images_path}icon_open.gif\"  border=\"0\" alt=\"\">
						</td>
					</tr>
					</table>
				</div>
			</td>
" . (($this->ipsclass->vars['_remove_emoticons']==0) ? ("
			<td>
				<div class='rte-menu-button' id='{$editor_id}_popup_emoticons' title='{$this->ipsclass->lang['js_tt_emoticons']}' style='margin-right:4px;width:41px'>
					<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\">
					<tr>
						<td><div id='{$editor_id}_out_emoticons'>&nbsp;</div></td>
						<td nowrap=\"nowrap\">
							<img class='ipd' src=\"{$images_path}rte-emoticon.gif\" alt=\"{$this->ipsclass->lang['js_tt_emoticons']}\" title=\"{$this->ipsclass->lang['js_tt_emoticons']}\" >
							<img class=\"ipd\" src=\"{$images_path}icon_open.gif\"  border=\"0\" alt=\"\">
						</td>
					</tr>
					</table>
				</div>
			</td>
") : ("")) . "
			<td><div class=\"rte-normal\" id=\"{$editor_id}_cmd_createlink\"><img src=\"{$images_path}rte-link-button.png\"  alt=\"{$this->ipsclass->lang['js_rte_lite_link']}\" title=\"{$this->ipsclass->lang['js_rte_lite_link']}\"></div></td>
			<td><div class=\"rte-normal\" id=\"{$editor_id}_cmd_insertimage\"><img src=\"{$images_path}rte-image-button.png\"  alt=\"{$this->ipsclass->lang['js_rte_lite_img']}\" title=\"{$this->ipsclass->lang['js_rte_lite_img']}\"></div></td>
			<td><div class=\"rte-normal\" id=\"{$editor_id}_cmd_insertemail\"><img src=\"{$images_path}rte-email-button.png\"  alt=\"{$this->ipsclass->lang['js_rte_lite_email']}\" title=\"{$this->ipsclass->lang['js_rte_lite_email']}\"></div></td>
			<td><div class=\"rte-normal\" id=\"{$editor_id}_cmd_ipb_quote\"><img src=\"{$images_path}rte-quote-button.png\"  alt=\"{$this->ipsclass->lang['js_rte_lite_quote']}\" title=\"{$this->ipsclass->lang['js_rte_lite_quote']}\"></div></td>
			<td><div class=\"rte-normal\" id=\"{$editor_id}_cmd_ipb_code\"><img src=\"{$images_path}rte-code-button.png\"  alt=\"{$this->ipsclass->lang['js_rte_lite_code']}\" title=\"{$this->ipsclass->lang['js_rte_lite_code']}\"></div></td>
			<td><img class=\"rteVertSep\" src=\"{$images_path}rte_dots.gif\" width=\"1\" height=\"20\" border=\"0\" alt=\"\"></td>
			<td><div class=\"rte-normal\" onclick=\"insert_update()\" style=\"font-weight: bold; color: #f00;\">Update</div></td>
			<td><img class=\"rteVertSep\" src=\"{$images_path}rte_dots.gif\" width=\"1\" height=\"20\" border=\"0\" alt=\"\"></td>
			<td><div class=\"rte-normal\" onclick=\"ShowHide_tag()\">Раскрывающийся текст</div></td>
            </tr>
          </table>
         </td>
         <td width='98%'>&nbsp;</td>
         <td width='1%' nowrap='nowrap' align='right'>
          <table cellpadding='0' cellspacing='0' width='100%'>
           <tr>
           	   <td><div class=\"rte-normal\" id=\"{$editor_id}_cmd_outdent\"><img src=\"{$images_path}rte-outdent.gif\" alt=\"{$this->ipsclass->lang['js_tt_outdent']}\" title=\"{$this->ipsclass->lang['js_tt_outdent']}\" ></div></td>
           	   <td><div class=\"rte-normal\" id=\"{$editor_id}_cmd_indent\"><img src=\"{$images_path}rte-indent.gif\" alt=\"{$this->ipsclass->lang['js_tt_indent']}\" title=\"{$this->ipsclass->lang['js_tt_indent']}\" ></div></td>
			   <td><img class=\"rteVertSep\" src=\"{$images_path}rte_dots.gif\" width=\"1\" height=\"20\" border=\"0\" alt=\"\"></td>
               <td><div class=\"rte-normal\" id=\"{$editor_id}_cmd_justifyleft\"><img src=\"{$images_path}rte-align-left.png\" alt=\"{$this->ipsclass->lang['js_tt_left']}\" title=\"{$this->ipsclass->lang['js_tt_left']}\" ></div></td>
               <td><div class=\"rte-normal\" id=\"{$editor_id}_cmd_justifycenter\"><img src=\"{$images_path}rte-align-center.png\" alt=\"{$this->ipsclass->lang['js_tt_center']}\" title=\"{$this->ipsclass->lang['js_tt_center']}\" ></div></td>
               <td><div class=\"rte-normal\" id=\"{$editor_id}_cmd_justifyright\"><img src=\"{$images_path}rte-align-right.png\" alt=\"{$this->ipsclass->lang['js_tt_right']}\" title=\"{$this->ipsclass->lang['js_tt_right']}\" ></div></td>
               <td><div class=\"rte-normal\" id=\"{$editor_id}_cmd_justifyfull\"><img src=\"{$images_path}rte-justify.png\" alt=\"{$this->ipsclass->lang['js_tt_jfull']}\" title=\"{$this->ipsclass->lang['js_tt_jfull']}\" ></div></td>
               <td><img class=\"rteVertSep\" src=\"{$images_path}rte_dots.gif\" width=\"1\" height=\"20\" border=\"0\" alt=\"\"></td>
               <td><div class=\"rte-normal\" id=\"{$editor_id}_cmd_insertorderedlist\"><img src=\"{$images_path}rte-list-numbered.gif\" alt=\"{$this->ipsclass->lang['js_tt_list']}\" title=\"{$this->ipsclass->lang['js_tt_list']}\" ></div></td>
               <td><div class=\"rte-normal\" id=\"{$editor_id}_cmd_insertunorderedlist\"><img src=\"{$images_path}rte-list.gif\" alt=\"{$this->ipsclass->lang['js_tt_list']}\" title=\"{$this->ipsclass->lang['js_tt_list']}\" ></div></td>
           </tr>
          </table>
         </td>
        </tr>
        </table>
<!-- ============================================================= -->
        <table cellpadding=\"2\" cellspacing=\"0\" id=\"Buttons3\" width='100%'>
        <tr>
         <td width='1%' align='left' nowrap='nowrap'>
          <table cellpadding='0' cellspacing='0' width='100%'>
           <tr>
             <td><div class=\"rte-normal\"><img src='http://img.combats.com/i/inf1.gif' width='12' height='11' alt='Morgenshtern' title='Вставить ник игрока из Capital' onclick='tag_player(1)' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.com/i/inf2.gif' width='12' height='11' alt='Morgenshtern' title='Вставить ник игрока из Angels ' onclick='tag_player(2)' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.com/i/inf3.gif' width='12' height='11' alt='Morgenshtern' title='Вставить ник игрока из Demons' onclick='tag_player(3)' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.com/i/inf4.gif' width='12' height='11' alt='Morgenshtern' title='Вставить ник игрока из Devils' onclick='tag_player(4)' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.com/i/inf5.gif' width='12' height='11' alt='Morgenshtern' title='Вставить ник игрока из Sun' onclick='tag_player(5)' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.com/i/inf6.gif' width='12' height='11' alt='Morgenshtern' title='Вставить ник игрока из Emerald' onclick='tag_player(6)' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.com/i/inf7.gif' width='12' height='11' alt='Morgenshtern' title='Вставить ник игрока из Sand' onclick='tag_player(7)' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.com/i/inf8.gif' width='12' height='11' alt='Morgenshtern' title='Вставить ник игрока из Moon' onclick='tag_player(8)' style=\"cursor: hand\"></div></td>
             <!--<td><div class=\"rte-normal\"><img src='http://img.combats.com/i/inf9.gif' width='12' height='11' alt='Morgenshtern' title='Вставить ник игрока из ' onclick='tag_player(9)' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.com/i/inf10.gif' width='12' height='11' alt='Morgenshtern' title='Вставить ник игрока из ' onclick='tag_player(10)' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.com/i/inf12.gif' width='12' height='11' alt='Morgenshtern' title='Вставить ник игрока из ' onclick='tag_player(12)' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.com/i/inf13.gif' width='12' height='11' alt='Morgenshtern' title='Вставить ник игрока из ' onclick='tag_player(13)' style=\"cursor: hand\"></div></td>-->
             <td><div class=\"rte-normal\"><img src='http://img.combats.com/i/inf14.gif' width='12' height='11' alt='Morgenshtern' title='Вставить ник игрока из Low, Old, Dreams' onclick='tag_player(14)' style=\"cursor: hand\"></div></td>
	    <!--/SEP-->
             <td><div class=\"rte-normal\"><img src='http://images.morgenshtern.com/gerb/capital_small.gif' alt='Morgenshtern' title='CapitalCity' onclick='city_gerb(\"capital\")' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://images.morgenshtern.com/gerb/angels_small.gif' alt='Morgenshtern' title='AngelsCity' onclick='city_gerb(\"angels\")' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://images.morgenshtern.com/gerb/demons_small.gif' alt='Morgenshtern' title='DemonsCity' onclick='city_gerb(\"demons\")' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://images.morgenshtern.com/gerb/devils_small.gif' alt='Morgenshtern' title='DevilsCity' onclick='city_gerb(\"devils\")' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://images.morgenshtern.com/gerb/sun_small.gif' alt='Morgenshtern' title='SunCity' onclick='city_gerb(\"sun\")' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://images.morgenshtern.com/gerb/emeralds_small.gif' alt='Morgenshtern' title='EmeraldsCity' onclick='city_gerb(\"emeralds\")' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://images.morgenshtern.com/gerb/sand_small.gif' alt='Morgenshtern' title='SandCity' onclick='city_gerb(\"sand\")' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://images.morgenshtern.com/gerb/moon_small.gif' alt='Morgenshtern' title='MoonCity' onclick='city_gerb(\"moon\")' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://images.morgenshtern.com/gerb/east_small.gif' alt='Morgenshtern' title='EastCity' onclick='city_gerb(\"east\")' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://images.morgenshtern.com/gerb/newcapital_small.gif' alt='Morgenshtern' title='NewCapitalCity' onclick='city_gerb(\"newcapital\")' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://images.morgenshtern.com/gerb/abandon_small.gif' alt='Morgenshtern' title='Abandoned Plain' onclick='city_gerb(\"abandon\")' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://images.morgenshtern.com/gerb/dreams_small.gif' alt='Morgenshtern' title='DreamsCity' onclick='city_gerb(\"dreams\")' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://images.morgenshtern.com/gerb/low_small.gif' alt='Morgenshtern' title='LowCity' onclick='city_gerb(\"low\")' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://images.morgenshtern.com/gerb/old_small.gif' alt='Morgenshtern' title='OldCity' onclick='city_gerb(\"old\")' style=\"cursor: hand\"></div></td>
	    <!--SEP-->
             <td><div class=\"rte-normal\"><img class=\"rteVertSep\" src=\"{ipb.vars['img_url']}/folder_rte_images/rte_dots.gif\" width=\"3\" height=\"15\" border=\"0\" alt=\"\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.com/i/align1.gif' width='12' height='15' alt='Morgenshtern' title='' onclick='tag_align(\"align1\")' style=\"cursor: hand\">&nbsp;</div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.com/i/align3.gif' width='12' height='15' alt='Morgenshtern' title='' onclick='tag_align(\"align3\")' style=\"cursor: hand\">&nbsp;</div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.com/i/align7.gif' width='12' height='15' alt='Morgenshtern' title='' onclick='tag_align(\"align7\")' style=\"cursor: hand\">&nbsp;</div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.com/i/align2.gif' width='12' height='15' alt='Morgenshtern' title='' onclick='tag_align(\"align2\")' style=\"cursor: hand\">&nbsp;</div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.com/i/align2.9.gif' width='12' height='15' alt='Morgenshtern' title='' onclick='tag_align(\"align2.9\")' style=\"cursor: hand\">&nbsp;</div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.com/i/align2.99.gif' width='12' height='15' alt='Morgenshtern' title='' onclick='tag_align(\"align2.99\")' style=\"cursor: hand\">&nbsp;</div></td>
             <td><div class=\"rte-normal\">&nbsp;<img src='http://img.combats.com/i/align1.99.gif' width='12' height='15' alt='Morgenshtern' title='' onclick='tag_align(\"align1.99\")' style=\"cursor: hand\">&nbsp;</div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.com/i/align1.92.gif' width='12' height='15' alt='Morgenshtern' title='' onclick='tag_align(\"align1.92\")' style=\"cursor: hand\">&nbsp;</div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.com/i/align1.91.gif' width='12' height='15' alt='Morgenshtern' title='' onclick='tag_align(\"align1.91\")' style=\"cursor: hand\">&nbsp;</div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.com/i/align1.9.gif' width='12' height='15' alt='Morgenshtern' title='' onclick='tag_align(\"align1.9\")' style=\"cursor: hand\">&nbsp;</div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.com/i/align1.75.gif' width='12' height='15' alt='Morgenshtern' title='' onclick='tag_align(\"align1.75\")' style=\"cursor: hand\">&nbsp;</div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.com/i/align1.7.gif' width='12' height='15' alt='Morgenshtern' title='' onclick='tag_align(\"align1.7\")' style=\"cursor: hand\">&nbsp;</div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.com/i/align1.6.gif' width='12' height='15' alt='Morgenshtern' title='' onclick='tag_align(\"align1.6\")' style=\"cursor: hand\">&nbsp;</div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.com/i/align1.5.gif' width='12' height='15' alt='Morgenshtern' title='' onclick='tag_align(\"align1.5\")' style=\"cursor: hand\">&nbsp;</div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.com/i/align1.4.gif' width='12' height='15' alt='Morgenshtern' title='' onclick='tag_align(\"align1.4\")' style=\"cursor: hand\">&nbsp;</div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.com/i/align1.1.gif' width='12' height='15' alt='Morgenshtern' title='' onclick='tag_align(\"align1.1\")' style=\"cursor: hand\">&nbsp;</div></td>
             <td><div class=\"rte-normal\">&nbsp;<img src='http://img.combats.com/i/align3.99.gif' width='12' height='15' alt='Morgenshtern' title='' onclick='tag_align(\"align3.99\")' style=\"cursor: hand\">&nbsp;</div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.com/i/align3.091.gif' width='12' height='15' alt='Morgenshtern' title='' onclick='tag_align(\"align3.091\")' style=\"cursor: hand\">&nbsp;</div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.com/i/align3.09.gif' width='12' height='15' alt='Morgenshtern' title='' onclick='tag_align(\"align3.09\")' style=\"cursor: hand\">&nbsp;</div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.com/i/align3.07.gif' width='12' height='15' alt='Morgenshtern' title='' onclick='tag_align(\"align3.07\")' style=\"cursor: hand\">&nbsp;</div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.com/i/align3.06.gif' width='12' height='15' alt='Morgenshtern' title='' onclick='tag_align(\"align3.06\")' style=\"cursor: hand\">&nbsp;</div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.com/i/align3.05.gif' width='12' height='15' alt='Morgenshtern' title='' onclick='tag_align(\"align3.05\")' style=\"cursor: hand\">&nbsp;</div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.com/i/align3.01.gif' width='12' height='15' alt='Morgenshtern' title='' onclick='tag_align(\"align3.01\")' style=\"cursor: hand\">&nbsp;</div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.com/i/klan/Morgenshtern.gif' width='24' height='15' alt='Morgenshtern' title='Вставить значок клана' onclick='tag_clan()' style=\"cursor: hand\"></div></td>
        </tr>
        </table>
<!-- ============================================================= -->
        <table cellpadding=\"2\" cellspacing=\"0\" id=\"Buttons4\" width='100%'>
        <tr>
         <td width='1%' align='left' nowrap='nowrap'>
          <table cellpadding='0' cellspacing='0' width='100%'>
           <tr>
             <td><div class=\"rte-normal\"><img src='http://img.combats.ru/i/misc/zn1_1.gif' width='35' height='24' alt='Morgenshtern' title='' onclick='dungeon_gerb(1, 1)' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.ru/i/misc/zn2_1.gif' width='35' height='24' alt='Morgenshtern' title='' onclick='dungeon_gerb(2, 1)' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.ru/i/misc/zn3_1.gif' width='35' height='24' alt='Morgenshtern' title='' onclick='dungeon_gerb(3, 1)' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.ru/i/misc/zn4_1.gif' width='35' height='24' alt='Morgenshtern' title='' onclick='dungeon_gerb(4, 1)' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.ru/i/misc/zn5_1.gif' width='35' height='24' alt='Morgenshtern' title='' onclick='dungeon_gerb(5, 1)' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.ru/i/misc/zn6_1.gif' width='35' height='24' alt='Morgenshtern' title='' onclick='dungeon_gerb(6, 1)' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.ru/i/misc/zn7_1.gif' width='35' height='24' alt='Morgenshtern' title='' onclick='dungeon_gerb(7, 1)' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.ru/i/misc/zn8_1.gif' width='35' height='24' alt='Morgenshtern' title='' onclick='dungeon_gerb(8, 1)' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.ru/i/misc/zn9_1.gif' width='35' height='24' alt='Morgenshtern' title='' onclick='dungeon_gerb(9, 1)' style=\"cursor: hand\"></div></td>
	    <!--SEP-->
             <td><div class=\"rte-normal\"><img src='http://img.combats.ru/i/misc/zn1_2.gif' width='35' height='24' alt='Morgenshtern' title='' onclick='dungeon_gerb(1, 2)' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.ru/i/misc/zn2_2.gif' width='35' height='24' alt='Morgenshtern' title='' onclick='dungeon_gerb(2, 2)' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.ru/i/misc/zn3_2.gif' width='35' height='24' alt='Morgenshtern' title='' onclick='dungeon_gerb(3, 2)' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.ru/i/misc/zn4_2.gif' width='35' height='24' alt='Morgenshtern' title='' onclick='dungeon_gerb(4, 2)' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.ru/i/misc/zn5_2.gif' width='35' height='24' alt='Morgenshtern' title='' onclick='dungeon_gerb(5, 2)' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.ru/i/misc/zn6_2.gif' width='35' height='24' alt='Morgenshtern' title='' onclick='dungeon_gerb(6, 2)' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.ru/i/misc/zn7_2.gif' width='35' height='24' alt='Morgenshtern' title='' onclick='dungeon_gerb(7, 2)' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.ru/i/misc/zn8_2.gif' width='35' height='24' alt='Morgenshtern' title='' onclick='dungeon_gerb(8, 2)' style=\"cursor: hand\"></div></td>
             <td><div class=\"rte-normal\"><img src='http://img.combats.ru/i/misc/zn9_2.gif' width='35' height='24' alt='Morgenshtern' title='' onclick='dungeon_gerb(9, 2)' style=\"cursor: hand\"></div></td>
        </tr>
        </table>
<!-- ============================================================= -->
    </div>
	<div style='padding:6px'>
    	<textarea name=\"{$form_field}\" class=\"rte-iframe\" id=\"{$editor_id}_textarea\" rows=\"10\" cols=\"60\" style=\"width:98%; height:250px\" tabindex=\"3\">$initial_content</textarea>
	</div>
	<div style='float:right;padding:1px 8px 4px 8px'>
		<div class='rte-menu-button' style='width:108px;font-size:10px;padding-right:8px;text-align:left;'><a href=\"javascript:bbc_pop()\" style='text-decoration:none;text-align:left'><img src=\"{$images_path}rte-bbcode-help-sm.png\" style='vertical-align:middle' alt='Help' border='0' /> {$this->ipsclass->lang['bbc_help']}</a></div>
	</div>
	<div align='left' style='padding:1px 8px 4px 8px; height:28px'>
		<div id='rte-toggle-side-panel-button' class='rte-menu-button' style='width:135px;font-size:10px;padding-right:8px'><a href='#' onclick=\"return show_options_panel('{$editor_id}')\" style='text-decoration:none'><img src=\"{$images_path}rte-toggle-options.png\" alt='Help' border='0' /> {$this->ipsclass->lang['toggle_side_panel']}</a></div>
	</div>
	
</td></tr></table>
<br />
<script type=\"text/javascript\">
<!--
var MessageMax          = parseInt(\"{$this->ipsclass->lang['the_max_length']}\");
var Override            = \"{$this->ipsclass->lang['override']}\";
// Global paths and data
var global_rte_remove_side_panel = parseInt(\"{$this->ipsclass->vars['_remove_side_panel']}\");
var global_rte_side_panel_open   = parseInt(\"{$this->ipsclass->vars['rte_side_panel_open']}\");
var global_rte_images_url        = '$images_path';
var global_rte_includes_url      = '$inc_path';
var global_rte_emoticons_url     = '{$this->ipsclass->vars['EMOTICONS_URL']}';
var global_rte_char_set          = '{$this->ipsclass->vars['gb_char_set']}';
// Lang array
ips_language_array =
{
	'js_rte_link'          : \"{$this->ipsclass->lang['js_rte_link']}\",
	'js_rte_unlink'        : \"{$this->ipsclass->lang['js_rte_unlink']}\",
	'js_rte_image'         : \"{$this->ipsclass->lang['js_rte_image']}\",
	'js_rte_email'         : \"{$this->ipsclass->lang['js_rte_email']}\",
    'js_rte_erroriespell'  : \"{$this->ipsclass->lang['js_rte_erroriespell']}\",
	'js_rte_errorliespell' : \"{$this->ipsclass->lang['js_rte_errorliespell']}\",
	'js_rte_code'          : \"{$this->ipsclass->lang['js_rte_code']}\",
	'js_rte_quote'         : \"{$this->ipsclass->lang['js_rte_quote']}\",
	'js_rte_sub'           : \"{$this->ipsclass->lang['js_tt_sub']}\",
	'js_rte_sup'           : \"{$this->ipsclass->lang['js_tt_sup']}\",
	'js_rte_strike'        : \"{$this->ipsclass->lang['js_tt_strike']}\",
	'emos_show_all'		   : \"{$this->ipsclass->lang['emos_show_all']}\",
	'emos_show_prev'	   : \"{$this->ipsclass->lang['emos_show_prev']}\",
	'emos_show_next'	   : \"{$this->ipsclass->lang['emos_show_next']}\",
	'ed_quick_access'	   : \"{$this->ipsclass->lang['ed_quick_access']}\",
	'insert_prefix'		   : \"{$this->ipsclass->lang['insert_prefix']}\"
};
// Smilies array
ips_smilie_items =
{
	$smilies
};
// BBcode items
ips_bbcode_items =
{
	$bbcode
};
// INIT item
IPS_editor['{$editor_id}'] = new ips_text_editor( '{$editor_id}', parseInt($rte_mode), parseInt($rte_mode) == 1 ? 0 : 1 );
// Set up defaults
IPS_editor['{$editor_id}'].allow_advanced        = 0;
IPS_editor['{$editor_id}'].forum_fix_ie_newlines = 1;
// Add bbcode items
for( var i in ips_bbcode_items )
{
	IPS_editor['{$editor_id}'].module_add_item( 'bbcodeloader{id=' + i + '}', \"{$this->ipsclass->lang['insert_prefix']}\" + ips_bbcode_items[ i ]['title'] , 'rte-ipd-tag.png' );
}
// Bothering with the insert special menu?
var _c = 0;
for ( var i in IPS_editor['{$editor_id}'].ips_special_items )
{
	_c++;
}
if ( _c < 1 )
{
	document.getElementById( '{$editor_id}' + '_popup_special' ).style.display = 'none';
}
// Check side panel
check_side_panel( '{$editor_id}' );
-->
</script>";
//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>
editor_std,ips_editor
</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>