<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 3                     */
/* CACHE FILE: Generated: Thu, 24 May 2007 13:16:02 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_gallery_img_3 {

 var $ipsclass;
//===========================================================================
// <ips:ecard:desc::trigger:>
//===========================================================================
function ecard($info="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<form method=\"post\" id='postingform' action=\"{ipb.script_url}\" name=\"REPLIER\" onsubmit='return ValidateForm()'>
	<input type=\"hidden\" name=\"automodule\" value=\"gallery\" />
	<input type=\"hidden\" name=\"cmd\" value=\"ecard\" />
	<input type=\"hidden\" name=\"img\" value=\"{ipb.input['img']}\" />
	<input type=\"hidden\" name=\"op\" value=\"ecardpreview\" />
	<div class=\"borderwrap\">
		<div class=\"maintitle\"><{CAT_IMG}>&nbsp;{ipb.lang['ecard']} {$info['caption']}</div>
		<table width=\"100%\" class='ipbtable'>
		<tr>
		  <td colspan=\"2\" align=\"center\" class=\"bgl\">
		   <div style=\"width:100%;\" align=\"center\" class=\"borderwrap\">
		   <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"darkrow3\">
			  <tr>
				  <td align=\"right\" width=\"20%\"><strong>{ipb.lang['receiver_name']}</strong></td>
				  <td align=\"left\" width=\"80%\"><input type=\"text\" size='50' name=\"receiver_name\" value=\"{ipb.input['receiver_name']}\" /></td>
			  </tr>
		  </table>
		  </div>
		  </td>
	    </tr>
	    <tr>
		  <td colspan=\"2\" align=\"center\" class=\"bgl\">
		   <div style=\"width:100%;\" align=\"center\" class=\"borderwrap\">
		   <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"darkrow3\">
			  <tr>
				  <td align=\"right\" width=\"20%\"><strong>{ipb.lang['receiver_email']}</strong></td>
				  <td align=\"left\" width=\"80%\"><input type=\"text\" size='50' name=\"receiver_email\" value=\"{ipb.input['receiver_email']}\" /></td>
			  </tr>
		  </table>
		  </div>
		  </td>
	    </tr>
	    <tr>
		  <td colspan=\"2\" align=\"center\" class=\"bgl\">
		   <div style=\"width:100%;\" align=\"center\" class=\"borderwrap\">
		   <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"darkrow3\">
			  <tr>
				  <td align=\"right\" width=\"20%\"><strong>{ipb.lang['ecard_subject']}</strong></td>
				  <td align=\"left\" width=\"80%\"><input type=\"text\" size='50' name=\"subject\" value=\"{ipb.input['subject']}\" /></td>
			  </tr>
		  </table>
		  </div>
		  </td>
	    </tr>
	    
	    <tr>
		  <td colspan=\"2\" align=\"center\" class=\"bgl\">
		   <div style=\"width:100%;\" align=\"center\" class=\"borderwrap\">
		   <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"darkrow3\">
			  <tr>
				  <td align=\"right\" width=\"20%\"><strong>{ipb.lang['ecard_colors']}</strong></td>
				  <td align=\"left\" width=\"80%\">{$info['bg']} {$info['border']} {$info['font']}</td>
			  </tr>
		  </table>
		  </div>
		  </td>
	    </tr>
		
		
		<tr>
         <td colspan=\"2\" align=\"center\" class=\"bgl\">
         <div style=\"width:100%;\" align=\"center\" class=\"borderwrap\">
         <table cellpadding=\"5\" cellspacing=\"5\" width=\"100%\" class=\"darkrow3\">
             <tr>
			<td align=\"right\" valign=\"top\" width=\"20%\">
				<!--SMILIE TABLE-->
			</td>
			<td align=\"left\" valign=\"top\" width=\"80%\">
                {$info['editor_html']}
            </td></tr>
   		 </table>
   		 </div>
		 </td>
		</tr>
		
		<tr>
			<td class=\"formbuttonrow\" colspan=\"2\">
				<input type=\"submit\" name=\"submit\" value=\"{ipb.lang['ecard_preview']}\" />
			</td>
		</tr>
	  </table>
	</div>
</form>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:ecard_end:desc::trigger:>
//===========================================================================
function ecard_end() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "</body>
</html>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:ecard_preview:desc::trigger:>
//===========================================================================
function ecard_preview($info="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"borderwrap\">
	<div class=\"maintitle\"><{CAT_IMG}>&nbsp;{$info['lang']}</div>
<table cellspacing=\"1\" width=\"100%\">
	<tr>
		<td width=\"100%\" class=\"row1\"><center><h1>{$info['caption']}</h1>{$info['image']}</center>
			<span style=\"color: {$info['font']};\">
				<p style=\"border-color: {$info['border']}; background: {$info['bg']}\"><b>{$info['title']}</b><br /><br />{$info['msg']}</p>
			</span>
<b>{$info['sender']}</b>
		</td>
	</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:ecard_preview_options:desc::trigger:>
//===========================================================================
function ecard_preview_options($info="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
	<td class=\"row2\" colspan=\"2\">
	<b>{ipb.lang['ecard_p_receiver']}</b> {ipb.input['receiver_name']} ( {ipb.input['receiver_email']} )</td>
</tr>
<tr>
	<td class=\"formbuttonrow\" colspan=\"2\">
	<form name=\"colorform\" method=\"post\" action=\"?act=module\">
		<input type=\"hidden\" name=\"module\" value=\"gallery\" />
		<input type=\"hidden\" name=\"cmd\" value=\"ecard\" />
		<input type=\"hidden\" name=\"img\" value=\"{ipb.input['img']}\" />
		<input type=\"hidden\" name=\"op\" value=\"ecard\" />
		<input type=\"hidden\" name=\"receiver_name\" value=\"{ipb.input['receiver_name']}\" />
		<input type=\"hidden\" name=\"receiver_email\" value=\"{ipb.input['receiver_email']}\" />
		<input type=\"hidden\" name=\"subject\" value=\"{ipb.input['subject']}\" />
		<input type=\"hidden\" name=\"Post\" value=\"{ipb.input['Post']}\" />
		<input type=\"hidden\" name=\"bg\" value=\"{ipb.input['bg']}\" />
		<input type=\"hidden\" name=\"border\" value=\"{ipb.input['border']}\" />
		<input type=\"hidden\" name=\"font\" value=\"{ipb.input['font']}\" />
		<input type=\"submit\" name=\"submit\" value=\"{ipb.lang['ecard_modify']}\" />
	</form>&nbsp;
	<form name=\"colorform\" method=\"post\" action=\"?act=module\">
		<input type=\"hidden\" name=\"module\" value=\"gallery\" />
		<input type=\"hidden\" name=\"cmd\" value=\"ecard\" />
		<input type=\"hidden\" name=\"img\" value=\"{ipb.input['img']}\" />
		<input type=\"hidden\" name=\"op\" value=\"sendecard\" />
		<input type=\"hidden\" name=\"receiver_name\" value=\"{ipb.input['receiver_name']}\" />
		<input type=\"hidden\" name=\"receiver_email\" value=\"{ipb.input['receiver_email']}\" />
		<input type=\"hidden\" name=\"sender_name\" value=\"{ipb.input['sender_name']}\" />
		<input type=\"hidden\" name=\"sender_email\" value=\"{ipb.input['sender_email']}\" />
		<input type=\"hidden\" name=\"subject\" value=\"{ipb.input['subject']}\" />
		<input type=\"hidden\" name=\"Post\" value=\"{ipb.input['Post']}\" />
		<input type=\"hidden\" name=\"bg\" value=\"{ipb.input['bg']}\" />
		<input type=\"hidden\" name=\"border\" value=\"{ipb.input['border']}\" />
		<input type=\"hidden\" name=\"font\" value=\"{ipb.input['font']}\" />
		<input type=\"submit\" name=\"submit\" value=\"{ipb.lang['ecard_send']}\" />
	</form>
	</td>
</tr>
</table>
</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:ecard_top:desc::trigger:>
//===========================================================================
function ecard_top() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<html>
	<head>
		<title></title>
	</head>
	<body>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:page_end:desc::trigger:>
//===========================================================================
function page_end($info='') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<table cellspacing=\"1\" width=\"100%\">
	<tr>
		<td width=\"20%\" nowrap=\"nowrap\"><!--GALLERY_MOD_COMMENTS--></td>
		<td align=\"right\" width=\"80%\">
			<!--IBF.QUICK_REPLY_CLOSED--> 
			{$info['favorite_button']}&nbsp;{$info['ecard_button']}&nbsp;{$info['comment_button']}</td>
	</tr>
	<tr>
		<td colspan=\"2\">
		<!--IBF.QUICK_REPLY_OPEN-->
		</td>
	</tr>
</table>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:photostrip:desc::trigger:>
//===========================================================================
function photostrip($info="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class='borderwrap'>
<div class='maintitle'>{ipb.lang['photostrip']} {$info['name']}</div>
<div class='thumbwrap'>
<table width='100%' border='0' cellspacing='1' cellpadding='0'>
<tr>
{$info['images']}
</tr>
</table>
</div>
</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:photostrip_curr:desc::trigger:>
//===========================================================================
function photostrip_curr($img="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<td class='row2' align='center' valign='middle'>{$img}<br />&nbsp;</td>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:photostrip_noncurr:desc::trigger:>
//===========================================================================
function photostrip_noncurr($info="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<td class='post2' align='center' width='20%' valign='bottom'>
{$info['img']}<br />
{$info['control']}
</td>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:quick_reply_box_closed:desc::trigger:>
//===========================================================================
function quick_reply_box_closed() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<a href=\"javascript:ShowHide('qr_open','qr_closed');\" title=\"{ipb.lang['qr_open']}\" accesskey=\"f\"><{T_QREPLY}></a>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:quick_reply_box_open:desc::trigger:>
//===========================================================================
function quick_reply_box_open($fid="",$tid="",$show="hide",$key="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<script type=\"text/javascript\">
	<!--
		function emo_pop() {
			window.open('index.{ipb.vars['php_ext']}?act=legends&amp;CODE=emoticons&amp;s={ipb.session_id}','Legends','width=250,height=500,resizable=yes,scrollbars=yes'); 
		}
	//-->
</script>
<div id=\"qr_open\" style=\"display: $show; position: relative;\">
	<form name=\"REPLIER\" action=\"{ipb.script_url}\" method=\"post\">
		<input type=\"hidden\" name=\"automodule\" value=\"gallery\" />
		<input type=\"hidden\" name=\"cmd\" value=\"postcomment\" />
		<input type=\"hidden\" name=\"op\"  value=\"doaddcomment\" />
		<input type=\"hidden\" name=\"img\" value=\"{ipb.input['img']}\" />
		<!-- TITLE DIV -->
		<br /><a name=\"qr\" />
		<div class=\"borderwrap\">
			<div class=\"maintitle\"><{CAT_IMG}>&nbsp;{ipb.lang['qr_title']}</div>
			<!--<div class=\"tablepad\" style=\"width=90%;\" align=\"center\">-->
			<div style=\"padding: 6px; width:99%\" align=\"center\">
				<textarea id=\"fastreplyarea\" cols=\"70\" rows=\"8\" name=\"Post\" class=\"textinput\" tabindex=\"1\"></textarea>
				<br />
				<br />
				<a href=\"javascript:emo_pop();\">{ipb.lang['show_emo']}</a> 
				&#124; <input type=\"checkbox\" name=\"enableemo\" value=\"yes\" class=\"checkbox\" checked=\"checked\" />&nbsp;{ipb.lang['qr_add_smilie']} &#124; <input type=\"checkbox\" name=\"enablesig\" value=\"yes\" class=\"checkbox\" checked=\"checked\" />&nbsp;{ipb.lang['qr_add_sig']}
				<br />
				<br />
				<input type=\"submit\" name=\"submit\" value=\"{ipb.lang['qr_submit']}\" tabindex=\"2\" accesskey=\"s\" />&nbsp;<input type=\"submit\" name=\"preview\" value=\"{ipb.lang['qr_more_opts']}\" />&nbsp;&nbsp;<input type=\"button\" name=\"qrc\" onclick=\"ShowHide('qr_open','qr_closed');\" value=\"{ipb.lang['qr_closeit']}\" />
				
			</div>
		</div>
	</form>
</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:rate_form:desc::trigger:>
//===========================================================================
function rate_form($img="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<form method=\"post\" action=\"index.php\">
	<input type=\"hidden\" name=\"automodule\" value=\"gallery\" />
	<input type=\"hidden\" name=\"cmd\" value=\"rate\" />
	<input type=\"hidden\" name=\"img\" value=\"{$img}\" />
	<input type=\"hidden\" name=\"cat\" value=\"{ipb.input['cat']}\" />
	<input type=\"hidden\" name=\"album\" value=\"{ipb.input['album']}\" />
	<input type=\"hidden\" name=\"op\" value=\"dorate\" />
	<input type=\"radio\" name=\"rating\" value=\"5\" title=\"{ipb.lang['best']}\"  checked />&nbsp;5&nbsp;<input type=\"radio\" name=\"rating\" value=\"4\" />&nbsp;4&nbsp;<input type=\"radio\" name=\"rating\" value=\"3\" />&nbsp;3&nbsp;<input type=\"radio\" name=\"rating\" value=\"2\" />&nbsp;2&nbsp;<input type=\"radio\" name=\"rating\" value=\"1\" title=\"{ipb.lang['worst']}\" />&nbsp;1&nbsp;<input type=\"submit\" name=\"submit\" value=\"{ipb.lang['rateit']}\" />
</form>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:report_form:desc::trigger:>
//===========================================================================
function report_form($img="",$title="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<form action=\"{ipb.script_url}automodule=gallery&cmd=mod&op=doreportimg\" method=\"post\" name=\"REPLIER\">
<input type=\"hidden\" name=\"img\" value=\"{$img}\">
	<div class=\"borderwrap\">
		<div class=\"maintitle\"><{CAT_IMG}>&nbsp;{ipb.lang['report_img_page']}</div>
		<table cellspacing=\"1\">
			<tr>
				<td class=\"row1\"  width=\"30%\" valign=\"top\"><b>{ipb.lang['report_img_title']}</b></td>
				<td class=\"row1\" width=\"80%\"><a href=\"{ipb.script_url}automodule=gallery&cmd=si&img=$img\">$title</a>
				</td>
			</tr>
			<tr>
				<td class=\"row1\"  width=\"30%\" valign=\"top\">{ipb.lang['report_img_msg']}</td>
				<td class=\"row1\" width=\"80%\"><textarea cols=\"60\" rows=\"12\" wrap=\"soft\" name=\"message\" class=\"textinput\"></textarea>
				</td>
			</tr>
			<tr>
				<td class=\"formbuttonrow\" colspan=\"2\"><input type=\"submit\" value=\"{ipb.lang['report_submit']}\" /></td>
			</tr>
		</table>
	</div>
</form>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:show_image:desc::trigger:>
//===========================================================================
function show_image($info="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<script type=\"text/javascript\">
<!--
var ipb_lang_tt_prompt = \"{ipb.lang['tt_prompt']}\";
var ipb_lang_js_del_1  = \"{ipb.lang['js_del_1']}\";
var ipb_lang_js_del_2  = \"{ipb.lang['js_del_2']}\";
var lang_gobutton    = \"{ipb.lang['f_go']}\";
var lang_suredelete  = \"{ipb.lang['del_confirm']}\";
var lang_nodelete  = \"{ipb.lang['del_no_act']}\";
-->
</script>
<script type=\"text/javascript\" src=\"jscripts/ipb_galleryjs.js\"></script>
<table cellspacing=\"1\" width=\"100%\">
	<tr>
		<td width=\"20%\" nowrap=\"nowrap\">&nbsp;</td>
		<td align=\"right\" width=\"80%\">{$info['favorite_button']}&nbsp;{$info['ecard_button']}&nbsp;{$info['comment_button']}</td>
	</tr>
</table>
<div class=\"borderwrap\">
	<div class=\"maintitle\"><{CAT_IMG}>&nbsp;{$info['caption']}</div>
	<table cellspacing=\"1\" width=\"100%\">
		<tr> 
			<th width=\"33%\">{ipb.lang['uploaded_by']} {$info['author']} {ipb.lang['on']} {$info['date']}</th>
			<th align=\"right\" width=\"33%\">{ipb.lang['views']} {$info['views']} &middot; {ipb.lang['img_comments']} {$info['comments']}</th>          
		</tr>
		<tr>
			<td class=\"formsubtitle\">{$info['description']}</td>
			<td class=\"formsubtitle\" valign=\"top\" rowspan=\"2\" align=\"right\">{$info['rate']}</td>
		</tr>
		<tr><td class=\"formsubtitle\">
         " . ((info['copyright'] != '') ? ("
            <i>{$info['copyright']}</i><br />
           ") : ("")) . "
        " . ((info['credit_info'] !='') ? ("
       {ipb.lang['credit_line']} {$info['credit_info']}
    ") : ("")) . "
     </td></tr>
		<tr>
			<td colspan=\"2\" class=\"row2\">
				{$info['pin_button']}&nbsp;{$info['edit_button']}&nbsp;{$info['move_button']}&nbsp;{$info['delete_button']}{$info['report_button']}
			</td>
		</tr>
	</table>
</div>
<div class=\"fullimagewrap\">
	{$info['image']}
</div>
<table cellspacing=\"1\" width=\"100%\">
	<tr>
		<td width=\"20%\" nowrap=\"nowrap\">&nbsp;</td>
		<td align=\"right\" width=\"80%\">{$info['favorite_button']}&nbsp;{$info['ecard_button']}&nbsp;{$info['comment_button']}</td>
	</tr>
</table>";
//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>

</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>