<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 3                     */
/* CACHE FILE: Generated: Thu, 24 May 2007 13:16:02 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_gallery_cats_3 {

 var $ipsclass;
//===========================================================================
// <ips:active_users:desc::trigger:>
//===========================================================================
function active_users($online="",$totals="",$str="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
<td class='formsubtitle' colspan='2'>{$totals}</td></tr>
		<tr>
			<td class=\"row1\" width=\"1%\"><{F_ACTIVE}></td>
			<td class=\"row2\">{$str['reg']} {$str['guests']} {$str['anon']}
                           <div class=\"thin\">{$online}</div>
            </td>
		</tr>

		<tr>
			<td class=\"catend\" colspan=\"2\"><!-- no content --></td>
		</tr>
	</table>
</div>
<br />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:album_end:desc::trigger:>
//===========================================================================
function album_end() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<!-- no content -->";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:album_row:desc::trigger:>
//===========================================================================
function album_row($info="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr> 
			<td class=\"{$info['css']}\" align=\"center\" width=\"1%\">{$info['img_new_post']}</td>
			<td class=\"{$info['css']}\"><b><a href=\"{$info['link']}\">{$info['name']}</a></b><br /><span>{$info['description']}</span></td>
			<td class=\"{$info['css']}\" align=\"center\">{$info['member']}</td>
			<td class=\"{$info['css']}\" align=\"center\"><b>{$info['images']}</b></td>
			<td class=\"{$info['css']}\" align=\"center\"><b>{$info['comments']}</b></td>
			<td class=\"{$info['css']}\" nowrap=\"nowrap\">
				<span>{$info['last_pic']}<br />{ipb.lang['by']}: {$info['last_poster']}<br />{ipb.lang['on']} {$info['date']}</span>
			</td>
		</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:album_top:desc::trigger:>
//===========================================================================
function album_top() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr> 
			<th width=\"40%\" colspan=\"2\">{ipb.lang['album_name']}</th>
			<th align=\"center\" width=\"19%\">{ipb.lang['sort_name']}</th>
			<th align=\"center\" width=\"7%\">{ipb.lang['images']}</th>
			<th align=\"center\" width=\"7%\">{ipb.lang['comments']}</th>
			<th width=\"25%\">{ipb.lang['last_post_info']}</th>
		</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:approve_images_line:desc::trigger:>
//===========================================================================
function approve_images_line($num="",$approve_url="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class='ipbtable'>
	<a href=\"{$approve_url}\">{$num}</a></div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:cat_end:desc::trigger:>
//===========================================================================
function cat_end() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<!--cat_end.start-->
</table>


<br />


<!--cat_end.end-->";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:cat_end_tr:desc::trigger:>
//===========================================================================
function cat_end_tr() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:cat_page_end:desc::trigger:>
//===========================================================================
function cat_page_end() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<script type=\"text/javascript\" src='jscripts/ipb_galleryjs.js'></script>
<script type='text/javascript'>
//<![CDATA[
// Resize thumb divs...
var use_thumbs = parseInt(\"{ipb.vars['gallery_create_thumbs']}\");
var thumbs_x   = parseInt(\"{ipb.vars['gallery_thumb_width']}\");
var thumbs_y   = parseInt(\"{ipb.vars['gallery_thumb_height']}\");

html_resize_thumb_divs( use_thumbs, thumbs_x, thumbs_y );
//]]>
</script>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:cat_row:desc::trigger:>
//===========================================================================
function cat_row($info="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<!--skin_gallery_cats:cat_row.start-->
<td {$info['colspan']}width=\"{$info['cat_width']}\" valign=\"top\">
<div class=\"borderwrap\" id=\"fc_{$info['id']}\">

<table cellspacing=\"0\" cellpadding=\"3\" width=\"100%\">
<div class=\"maintitle\">{$info['has_subcats']}<u><a href=\"{$info['link']}\">{$info[ 'name' ]}</a></u> &nbsp; </div>
<div class=\"popupmenu\" id=\"sub_{$info['id']}\" style=\"position: absolute; display: none;\">
  <div class=\"popupmenu-item\">
  {$info['sub_cats']}
  </div>
</div>
<tr>
  <th colspan=\"2\">{ipb.lang['last_post_info']} {$info['date']}&nbsp;</th>
</tr>

  <tr>
  
  <td class=\"row2\" valign=\"middle\" align=\"center\" width=\"30%\">
      <table align=\"center\" cellpadding=\"3\" width=\"100%\" height=\"{ipb.vars['gallery_thumb_height']}\">
       <tr><td align=\"center\">
         {$info['last_pic']}</td></tr>
          <tr><td align=\"center\">{$info['photo_bar']}{$info['photo_info']}
          </td></tr>
      </table>
            </td>
            
            <td class=\"row1\" valign=\"middle\" width=\"75%\"><span class=\"postdetails\"><strong>{$info['description']}</strong>
            <br />
            {$info['desc_subcats']}<br />
             {$info['approve_images']}
            </span></td>
   </tr>
<tr>
  <th align=\"right\" colspan=\"2\"> <i>&nbsp;{$info['images']} {ipb.lang['images']}, {$info['comments']} {ipb.lang['comments']}</i></th>
</table></div></td>
<!--skin_gallery_cats:cat_row.end-->";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:cat_start_tr:desc::trigger:>
//===========================================================================
function cat_start_tr() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:cat_top:desc::trigger:>
//===========================================================================
function cat_top() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<br />
<style type=\"text/css\">
   .camera  {
         cursor: pointer;
         cursor: hand;
   }
</style>
  <table width=\"100%\" cellspacing=\"0\" cellpadding=\"1\" border=\"0\">";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:cat_view_end:desc::trigger:>
//===========================================================================
function cat_view_end($span="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr> 
			<td class=\"catend\" colspan=\"6\">{$span['multi_mod']}</td>
		</tr>
	</table>
</div>
<table cellspacing=\"1\" class=\"ipbtable\" width=\"100%\">
	<tr>
		<td width=\"20%\" nowrap=\"nowrap\">{$span['CATS']}<br /><br />{$span['SHOW_PAGES']}</td>
		<td align=\"right\" width=\"80%\">{$span['ss_button']} {$span['post_button']} {$span['multi_upload_button']}{$span['media_button']}</td>
	</tr>
</table>

<div class=\"borderwrap\">
	<div class=\"maintitle\"><{CAT_IMG}>&nbsp;{ipb.lang['sorting_options']}</div>
	<table cellspacing=\"1\" width=\"100%\">
		<tr> 
			<td class=\"row2\" align=\"center\">
<form method=\"post\" action=\"{ipb.script_url}\">
<input type=\"hidden\" name=\"automodule\" value=\"gallery\" />
<input type=\"hidden\" name=\"cmd\" value=\"sc\" />
<input type=\"hidden\" name=\"cat\" value=\"{ipb.input['cat']}\" />
<input type=\"hidden\" name=\"st\" value=\"{ipb.input['st']}\" />
<input type=\"hidden\" name=\"op\" value=\"{ipb.input['op']}\" />
{ipb.lang['showing']} {ipb.lang['sort_options']} 
<input type=\"submit\" name=\"submit\" value=\"{ipb.lang['go']}\" class=\"button\" />
				</form>
			</td>
		</tr>		
		<tr> 
			<td class=\"catend\">
			
</td>
		</tr>
	</table>
</div>
<br />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:cat_view_top:desc::trigger:>
//===========================================================================
function cat_view_top($info="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<table cellspacing=\"1\" class=\"ipbtable\" width=\"100%\">
	<tr>
		<td width=\"20%\" nowrap=\"nowrap\">{$info['CATS']}<br /><br />{$info['SHOW_PAGES']}</td>
		<td align=\"right\" width=\"80%\">{$info['ss_button']} {$info['post_button']} {$info['multi_upload_button']} {$info['media_button']}</td>
	</tr>
</table>

<div class=\"borderwrap\">
	<div class=\"maintitle\"><{CAT_IMG}>&nbsp;{$info['name']}</div>
	<table cellspacing=\"1\" class=\"ipbtable\" width=\"100%\">";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:index_list_end:desc::trigger:>
//===========================================================================
function index_list_end() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr> 
			<td class=\"catend\" colspan=\"5\"><!-- no content --></td>
		</tr>
	</table>
</div>
<br />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:index_list_top:desc::trigger:>
//===========================================================================
function index_list_top($name='') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"borderwrap\">
	<div class=\"maintitle\"><{CAT_IMG}>&nbsp;{$name}</div>
	<table cellspacing=\"1\" width=\"100%\" class=\"ipbtable\">";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:legacy_cat_end:desc::trigger:>
//===========================================================================
function legacy_cat_end($in="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr> 
			<td class=\"catend\" colspan=\"5\"><!-- no content --></td>
		</tr>
	</table>
</div>
<br />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:legacy_cat_header:desc::trigger:>
//===========================================================================
function legacy_cat_header($in="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"borderwrap\">
	<div class=\"maintitle\">
		<p><{CAT_IMG}>&nbsp;{ipb.lang['galleries']}</a></p>
	</div>
	<table class='ipbtable' cellspacing=\"1\">
		<tr> 
			<th colspan=\"2\" width=\"66%\">{ipb.lang['cat_name']}</th>
			<th align=\"center\" width=\"7%\">{ipb.lang['images']}</th>
			<th align=\"center\" width=\"7%\">{ipb.lang['comments']}</th>
			<th width=\"35%\">{ipb.lang['last_post_info']}</th>
		</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:legacy_cat_row:desc::trigger:>
//===========================================================================
function legacy_cat_row($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr> 
			<td align=\"center\" class=\"row2\" width=\"1%\" valign=\"middle\">{$data['img_new_post']}</td>
			<td class=\"row2\" valign=\"middle\"><b><a href=\"{$data['link']}\">{$data['name']}</a></b><br /><span class=\"forumdesc\">{$data['description']}{$data['desc_subcats']}<br /><i>{$data['approve_images']}</i></td>
			<td align=\"center\" class=\"row1\" valign=\"middle\"><b>{$data['images']}</b></td>
			<td align=\"center\" class=\"row1\" valign=\"middle\"><b>{$data['comments']}</b></td>
			<td class=\"row1\" nowrap=\"nowrap\" valign=\"middle\">{$data['last_pic']} <span><br /><b>{ipb.lang['by']}:</b> {$data['last_poster']}<br /><b>{ipb.lang['on']}</b>&nbsp;{$data['date']}</span></td>
		</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:multi_mod_form:desc::trigger:>
//===========================================================================
function multi_mod_form($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<form name=\"modform\" method=\"post\" action=\"index.php\">
	<input type=\"hidden\" name=\"automodule\" value=\"gallery\" />
	<input type=\"hidden\" name=\"cmd\" value=\"gallerymmod\" />
	<input type=\"hidden\" value=\"\" name=\"selectedimgids\" />
    <input type=\"hidden\" value=\"{ipb.input['cat']}\" name=\"cat\" />
    <div style='float:left;width:auto'>
	 <select name=\"galleryact\" id=\"galleryact\" onchange=\"check_move_select()\">
		 <option value=\"pin\">{ipb.lang['pin_images']}</option>
		 <option value=\"unpin\">{ipb.lang['unpin_images']}</option>
		 <option value=\"delete\">{ipb.lang['delete_images']}</option>
		 <option value=\"move\">{ipb.lang['move_images']}</option>
		 <option value=\"approve\">{ipb.lang['approve_images']}</option>
		 <option value=\"unapprove\">{ipb.lang['unapprove_images']}</option>
	 </select>
	</div>
	<div id='move_cat_div' style='display:none;position:relative;float:left;width:auto'>
	{$data}
	</div>
	<input type=\"submit\" name=\"gobutton\" value=\"{ipb.lang['mod_button']}\" class=\"button\" />
</form>
<script type=\"text/javascript\">
//<![CDATA[
	var move_cat_div = document.getElementById('move_cat_div');
	var galleryact   = document.getElementById('galleryact');
		
	function check_move_select()
	{
		for( var i = 0 ; i < galleryact.options.length ; i++ )
		{
			if ( galleryact.options[i].value == 'move' )
			{
				move_cat_div.style.display = ( galleryact.options[i].selected ) ? '' : 'none';
			}
		}
	}
//]]>
</script>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:search_form:desc::trigger:>
//===========================================================================
function search_form($txt='',$type='',$id=0) {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div id='userlinks'>
<form action='{ipb.script_url}' method='post'>
<input type='hidden' name='automodule' value='gallery'>
<input type='hidden' name='cmd' value='search'>
<input type='hidden' name='search_where' value='{$type}'>
<input type='hidden' name='search_where_id' value='{$id}'>

<p>
<b>
<i>{$txt}</i></b><input name='search_for' type='text' class='input'> 
<b>in</b>&nbsp;&nbsp;<select name='search_in'><option value='caption'>{ipb.lang['caption']}</option><option value='description' class='select'>{ipb.lang['description']}</option></select>
<input type='submit' name='submit' value='{ipb.lang['search_gallery']}'>
</p>
</form>
</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:ss_form:desc::trigger:>
//===========================================================================
function ss_form() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<script text=\"text/javascript\" src=\"jscripts/ipb_galleryjs.js\"></script>

<form method=\"post\" action=\"?automodule=gallery\">
	<input type=\"hidden\" name=\"cmd\" value=\"slideshow\" />
	<input type=\"hidden\" name=\"cat\" value=\"{ipb.input['cat']}\" />
	<input type=\"hidden\" name=\"album\" value=\"{ipb.input['album']}\" />	
	<input type=\"hidden\" name=\"show\" value=\"first\" />
	<div class=\"borderwrap\">
	<table cellspacing=\"1\" width=\"100%\">
		<tr>
			<td class=\"maintitle\" colspan=\"2\"><{CAT_IMG}>&nbsp;{ipb.lang['ss_options']}</td>
		</tr>
		<tr>
			<td width=\"35%\" class=\"row2\">
				<fieldset>
					<legend>{ipb.lang['ss_duration']}</legend>
					<input type=\"text\" name=\"duration\" value=\"5\" /> &nbsp;{ipb.lang['ss_seconds']}
				</fieldset> 
			</td>
			<td width=\"65%\" class=\"row2\">
				<fieldset>
					<legend>{ipb.lang['ss_sorting']}</legend>
					{ipb.lang['sort_options']}
				</fieldset>
			</td>
		</tr>
		<tr>
			<td class=\"formbuttonrow\" colspan=\"2\">
<input type='checkbox' name='hfoff' value='1'> {ipb.lang['ss_hfoff']}<br />
				<input onClick=\"start_slideshow();\" type=\"submit\" name=\"submit\" value=\"{ipb.lang['ss_go']}\" tabindex=\"4\" class=\"forminput\" accesskey=\"s\" />&nbsp;
			</td>
		</tr>
	</table>
	</div>
</form>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:ss_slide:desc::trigger:>
//===========================================================================
function ss_slide($photo='',$goto='',$img='') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<meta http-equiv=\"refresh\" content=\"{ipb.input['duration']}; url={$goto}\">
<div class=\"borderwrap\">
	<div class=\"maintitle\"><{CAT_IMG}>&nbsp;{ipb.lang['slideshow_start']}</div>
	<div class=\"row2\" style=\"padding: 4px; text-align: center;\"><b><a href=\"{ipb.script_url}automodule=gallery&cmd=si&img={$img}\">{ipb.lang['ss_stop']}</a></b></div>
</div>
<div class=\"fullimagewrap\">
	{$photo} 
</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:stats:desc::trigger:>
//===========================================================================
function stats($stats="",$active="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"borderwrap\">
	<div class=\"maintitle\"><{CAT_IMG}>&nbsp;{ipb.lang['stats']}</div>
	<table class=\"ipbtable\" cellspacing=\"1\" width=\"100%\">
	<tr>
		<th colspan='2' align='right'>
			<a href='{ipb.script_url}&act=module&module=gallery&cmd=stats&op=ratings'>{ipb.lang['top10']}</a> &middot; <a href='{ipb.script_url}&act=module&module=gallery&cmd=stats&op=views'>{ipb.lang['views10']}</a>
			&middot; <a href='{ipb.script_url}&act=module&module=gallery&cmd=stats&op=comments'>{ipb.lang['comments10']}</a>
		</th>
		<tr>
		 <td colspan='2' class='formsubtitle'>{ipb.lang['stats']}</td>
		</tr>
		<tr>
			<td class=\"row1\" width=\"1%\"><{F_STATS}></td>
			<td class=\"row2\">$stats</td>
		</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:stats_comment_row:desc::trigger:>
//===========================================================================
function stats_comment_row($info="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
<td width='20%' class='row1' align='center' valign='center'>
<div class='thumbwrap'>
{$info['image']}
</td>
</div>
<td width='80%' class='row2' 'align='left' valign='top'>
{$info['comment']}<br /><br />
<b>{ipb.lang['postedby']}</b> {$info['name']}<br /> <b>{ipb.lang['on']}</b> {$info['date']}</p>
</td>
</tr>";
//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>

</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>