<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 3                     */
/* CACHE FILE: Generated: Thu, 24 May 2007 13:16:02 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_gallery_comments_3 {

 var $ipsclass;
//===========================================================================
// <ips:button_delete:desc::trigger:>
//===========================================================================
function button_delete($pid='',$img='') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<a href='javascript:delete_img(\"{ipb.script_url}automodule=gallery&cmd=delcomment&comment={$pid}&img={ipb.input['img']}\")'><{P_DELETE}></a>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:button_edit:desc::trigger:>
//===========================================================================
function button_edit($pid='',$img='') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<a href=\"{ipb.script_url}automodule=gallery&cmd=editcomment&comment={$pid}&img={ipb.input['img']}\"><{P_EDIT}></a>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:CommentFooter:desc::trigger:>
//===========================================================================
function CommentFooter($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "</div>       
<table cellspacing=\"1\" class=\"ipbtable\" width=\"100%\">
	<tr>
		<td width=\"20%\" nowrap=\"nowrap\">{$data['SHOW_PAGES']}</td>
	</tr>
</table>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:CommentRow:desc::trigger:>
//===========================================================================
function CommentRow($post="",$author="",$is_mod='false') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<!--Begin Msg Number {$post['pid']}-->
<a name=\"{$post['pid']}\"></a>
<table class=\"ipbtable\" cellspacing=\"1\" width=\"100%\">
	<tr>
		<td valign=\"middle\" class=\"row2\" width=\"1%\"><a name=\"entry{$post['pid']}\"></a><span class=\"{$post['name_css']}\">{$author['name']}</span></td>
		<td class=\"row2\" valign=\"top\" width=\"99%\">
			<!-- POSTED DATE DIV -->
			<div style=\"float: left;\">
				<span class=\"postdetails\">{$post['post_icon']} <img src='{ipb.vars['img_url']}/to_post_off.gif' alt='post' border='0' style='padding-bottom:2px' /> {$post['post_date']}</span>
			</div>
			<!-- REPORT / DELETE / EDIT / QUOTE DIV -->
			<div align=\"right\">
				<span class=\"postdetails\">{$post['ip_address']} {ipb.lang['posted_on']}
					<a title=\"{ipb.lang['tt_link']}\" href=\"#\" onclick=\"gallery_link_to_post({$post['pid']}, {$post['img']} ); return false;\">#{$post['post_count']}</a>
" . ((is_mod == 'true') ? ("
&nbsp;&#0124;&nbsp;<a href=\"#\" title=\"Click to select this topic for bulk moderation\" onclick=\"gallery_toggle_pid('{$post['pid']}'); return false;\">{$post['pid_start_image']}</a>
") : ("")) . "

				</span>
			</div>
		</td>
	</tr>
	<tr>
		<td valign=\"top\" class=\"{$post['post_css']}\">
        	<span class=\"postdetails\">
        		{$author['avatar']}<br /><br />
        		{$author['title']}<br />
        		{$author['member_rank_img']}<br /><br />
        		{$author['member_group']}<br />
        		{$author['member_posts']}<br />
        		{$author['member_joined']}<br />
        		{$author['member_location']}
        		{$author['member_number']}<br />
" . ((author['custom_fields'] != "") ? ("
{$author['custom_fields']}
") : ("")) . "

<br />
        		{$author['warn_text']} {$author['warn_minus']}{$author['warn_img']}{$author['warn_add']}
        	</span><br />
        	<img src=\"{ipb.vars['img_url']}/spacer.gif\" alt=\"\" width=\"160\" height=\"1\" /><br /> 
       </td>
       <td width=\"100%\" valign=\"top\" class=\"{$post['post_css']}\">
			<!-- THE POST {$post['pid']} -->
			<div class=\"postcolor\">{$post['comment']} <!--IBF.ATTACHMENT_{$post['pid']}--></div>
				{$post['signature']}
			<!-- THE POST -->
		</td>
	</tr>
	<tr>
		<td class=\"formbuttonrow\" nowrap=\"nowrap\">
			<div style='text-align:left'>{$author['online_status_indicator']}{$author['addresscard']}{$author['message_icon']}<!--{$author['email_icon']}--></div>
		</td>
		<td class=\"formbuttonrow\" nowrap=\"nowrap\">
			<!-- PM / EMAIL / WWW / MSGR -->
			<div style=\"float: left;\">
				{$post['report_link']}<a href=\"javascript:scroll(0,0);\"><{P_UP}></a>
			</div>
			<!-- REPORT / UP -->
         	<div align=\"right\">
         		{$post['delete_button']}{$post['edit_button']}<a href=\"#\" onclick=\"multiquote_add({$post['pid']}); return false;\" title=\"{ipb.lang['mq_title']}\">{$post['mq_start_image']}</a><a href=\"{ipb.script_url}automodule=gallery&cmd=postcomment&img={ipb.input['img']}&gal_pids={$post['pid']}\" title=\"{ipb.lang['tt_reply_to_post']}\"><{P_QUOTE}></a>
         	</div>
         </td>
	</tr><tr>
	<td class=\"catend\" colspan=\"2\"><!-- no content --></td>
</tr>
</table>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:CommentTop:desc::trigger:>
//===========================================================================
function CommentTop($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<script type=\"text/javascript\" src=\"jscripts/ipb_topic.js\"></script>
<script type=\"text/javascript\" src=\"jscripts/ipb_galleryjs.js\"></script>
<a name=\"top\"></a>
<table cellspacing=\"1\" width=\"100%\" class=\"ipbtable\">
	<tr>
		<td nowrap=\"nowrap\">{$data['SHOW_PAGES']}</td>
	</tr>
</table>
<br />
<a name=\"comments\"></a>
<div class=\"borderwrap\">
	<div class=\"maintitle\"><{CAT_IMG}>&nbsp;<b>{ipb.lang['view_comments']}</b></div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:mod_form:desc::trigger:>
//===========================================================================
function mod_form() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"borderwrap\">
	<div class=\"tablepad\">
	<form name=\"modform\" method=\"post\" action=\"index.php\">
				<input type=\"hidden\" name=\"automodule\" value=\"gallery\" />
				<input type=\"hidden\" name=\"cmd\" value=\"gallerymmod\" />
                                <input type=\"hidden\" name=\"type\" value=\"comment\" />
				<input type=\"hidden\" value=\"\" name=\"selectedgcids\" />
                                <input type=\"hidden\" name=\"img\" value=\"{ipb.input['img']}\">
	<input type=\"hidden\" value=\"{ipb.input['cat']}\" name=\"cat\" />
				<select name=\"galleryact\">
					<option value=\"delcomments\">Delete Comments</option>
                                        <option value=\"approvecomments\">Approve Comments</option>
                                        <option value=\"unapprovecomments\">Unapprove Comments</option>
				</select>&nbsp;
				<input type=\"submit\" name=\"gobutton\" value=\"{ipb.lang['mod_button']}\" class=\"button\" />
			</form>
		</div>
	</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:mq_image_add:desc::trigger:>
//===========================================================================
function mq_image_add($pid='') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<img src=\"{ipb.vars['img_url']}/p_mq_add.gif\" name=\"mad_$pid\" alt=\"+\" />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:mq_image_remove:desc::trigger:>
//===========================================================================
function mq_image_remove($pid='') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<img src=\"{ipb.vars['img_url']}/p_mq_remove.gif\" name=\"mad_$pid\" alt=\"-\" />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:pid_image_selected:desc::trigger:>
//===========================================================================
function pid_image_selected($pid='') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<img name=\"pid{$pid}\" src=\"{ipb.vars['img_url']}/topic_selected.gif\" />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:pid_image_unselected:desc::trigger:>
//===========================================================================
function pid_image_unselected($pid='') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<img name=\"pid{$pid}\" src=\"{ipb.vars['img_url']}/topic_unselected.gif\" />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:report_comment_form:desc::trigger:>
//===========================================================================
function report_comment_form($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<form action=\"{ipb.script_url}automodule=gallery&cmd=mod&op=doreportcomment\" method=\"post\" name=\"REPLIER\">
<input type=\"hidden\" name=\"comment\" value=\"{$data['pid']}\" />
<input type=\"hidden\" name=\"st\" value=\"{$data['st']}\" />
	<div class=\"borderwrap\">
		<div class=\"maintitle\"><{CAT_IMG}>&nbsp;{ipb.lang['report_comment_page']}</div>
		<table class=\"ipbtable\" cellspacing=\"1\" width=\"100%\">
			<tr>
				<td class=\"row1\"  width=\"30%\" valign=\"top\">{ipb.lang['report_comment_msg']}</td>
				<td class=\"row1\" width=\"80%\"><textarea cols=\"60\" rows=\"12\" wrap=\"soft\" name=\"message\" class=\"textinput\"></textarea>
				</td>
			</tr>
			<tr>
				<td class=\"formbuttonrow\" colspan=\"2\"><input type=\"submit\" value=\"{ipb.lang['report_submit']}\" /></td>
			</tr>
		</table>
	</div>
</form>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:report_link:desc::trigger:>
//===========================================================================
function report_link($comment_id="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<a href=\"{ipb.script_url}automodule=gallery&cmd=mod&op=reportcomment&comment={$comment_id}&st={ipb.input['st']}\"><{P_REPORT}></a>";
//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>

</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>