<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 3                     */
/* CACHE FILE: Generated: Thu, 24 May 2007 13:16:02 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_gallery_albums_3 {

 var $ipsclass;
//===========================================================================
// <ips:album_form:desc::trigger:>
//===========================================================================
function album_form($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<form action=\"{ipb.script_url}\" method=\"post\" name=\"theForm\">
	<input type=\"hidden\" name=\"automodule\" value=\"gallery\" />
	<input type=\"hidden\" name=\"cmd\" value=\"albums\" />
	<input type=\"hidden\" name=\"op\" value=\"{$data['type_op']}\" />
	{$data['hiddens']}
	{$data['errors']}
	<div class=\"borderwrapm\">
		<div class=\"maintitle\">{ipb.lang['album_manage']}</div>
		<table cellspacing=\"1\" width=\"100%\">
			<td class=\"subtitle\" colspan=\"2\">{ipb.lang[ $data['type'] ]}</td>
			<tr>
				<td class=\"pformleft\">{ipb.lang['album_name']}</td>
				<td class=\"pformright\">
					<input type=\"text\" size=\"40\" maxlength=\"60\" name=\"name\" value=\"{$data['name']}\" />
				</td>
			</tr>  
			<tr>
				<td class=\"pformleft\">{ipb.lang['album_desc']}</td>
				<td class=\"pformright\">
					<input type=\"text\" size=\"40\" name=\"description\" value=\"{$data['description']}\" />
				</td>
			</tr>
" . ((data['q_cat'] == false) ? ("
<tr>
				<td class=\"pformleft\">{ipb.lang['cat_name']}</td>
				<td class=\"pformright\">
					{$data['cat_dropdown']}
				</td>
			</tr>
") : ("")) . "
<else>
<input type=\"hidden\" name=\"cat\" value=\"{ipb.input['cat']}\" />
</else>

			<tr>
				<td class=\"pformleft\">{ipb.lang['album_public']}</td>
				<td class=\"pformright\">
					<input type=\"checkbox\" name=\"public\" value=\"1\" class=\"checkbox\" {$data['public']} />&nbsp;{ipb.lang['album_public_chk']}
				</td>
			</tr>  
			<tr>
				<td class=\"formbuttonrow\" align=\"center\" colspan=\"2\">
					<input type=\"submit\" value=\"{$data['type']}\" class=\"button\" />
				</td>
			</tr>
		</table>
	</div>
</form>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:buddy_no_friends:desc::trigger:>
//===========================================================================
function buddy_no_friends() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr><td class=\"row2\"><b>
	{ipb.lang['gallery_nofriends']}
  		</b></td>
</tr>
</table><br />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:buddy_perms_buddy:desc::trigger:>
//===========================================================================
function buddy_perms_buddy($buddy="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr><td class=\"row1\" valign=\"top\" width=\"50%\">
<b><a href=\"javascript:gallery_toggleview( 'perm_{$buddy['contact_id']}' );\">{$buddy['contact_name']}</a>
  		</b>[ {$buddy['contact_desc']} ]
   <div id=\"perm_{$buddy['contact_id']}\" class=\"popupmenu\" style=\"position: relative; display:none;\">
  		<table class=\"ipbtable\">
  		<tr><th>VIEW</th><!--<th>EDIT</th><th>UPLOAD</th><th>DELETE</th>--></tr>
  		<tr>
  			<td align=\"center\"><input type=\"checkbox\" name=\"perm_view_{$buddy['contact_id']}\" {$buddy['perm_view']}/></td>
  			<!--<td align=\"center\"><input type=\"checkbox\" name=\"perm_edit_{$buddy['contact_id']}\" {$buddy['perm_edit']}/></td>
  			<td align=\"center\"><input type=\"checkbox\" name=\"perm_upload_{$buddy['contact_id']}\" {$buddy['perm_upload']}/></td>
  			<td align=\"center\"><input type=\"checkbox\" name=\"perm_delete_{$buddy['contact_id']}\" {$buddy['perm_delete']}/></td>-->
  		</tr>
  		</table>	
  	</div>
  			
  </td>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:buddy_perms_end:desc::trigger:>
//===========================================================================
function buddy_perms_end() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "</td></tr>
<tr><td colspan=\"2\" align=\"center\">
  <input type=\"submit\" name=\"formSubmit\" value=\"{ipb.lang['gallery_perms_submit']}\" /></form></td></tr>
</table>
<br />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:buddy_perms_perms_end:desc::trigger:>
//===========================================================================
function buddy_perms_perms_end($perms="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "</td></tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:buddy_perms_perms_row:desc::trigger:>
//===========================================================================
function buddy_perms_perms_row($perms="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<table class=\"ipbtable\">
  		<tr>
  			<td align=\"center\">VIEW: &nbsp;&nbsp;<img src=\"{ipb.vars['board_url']}/style_images/<#IMG_DIR#>/{$perms['perm_view']}\" border=\"0\" /></td>
  			<!--<td align=\"center\">EDIT: &nbsp;&nbsp;<img src=\"{ipb.vars['board_url']}/style_images/<#IMG_DIR#>/{$perms['perm_edit']}\" border=\"0\" /></td>
  			<td align=\"center\">UPLOAD: &nbsp;&nbsp;<img src=\"{ipb.vars['board_url']}/style_images/<#IMG_DIR#>/{$perms['perm_upload']}\" border=\"0\" /></td>
  			<td align=\"center\">DELETE: &nbsp;&nbsp;<img src=\"{ipb.vars['board_url']}/style_images/<#IMG_DIR#>/{$perms['perm_delete']}\" border=\"0\" /></td>-->
  			
  		</tr>
  		</table>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:buddy_perms_perms_st:desc::trigger:>
//===========================================================================
function buddy_perms_perms_st($perms="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<td class=\"row2\" valign=\"top\" width=\"50%\">";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:buddy_perms_start:desc::trigger:>
//===========================================================================
function buddy_perms_start($album="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"formsubtitle\">{ipb.lang['perms_album']}</div>
<script language=\"javascript\" src=\"jscripts/ipb_galleryjs.js\"></script>
<br />
<form action=\"{ipb.script_url}\" method=\"post\" name=\"theForm\">
	<input type=\"hidden\" name=\"automodule\" value=\"gallery\" />
	<input type=\"hidden\" name=\"cmd\" value=\"albums\" />
	<input type=\"hidden\" name=\"op\" value=\"buddyperms\" />
	<input type=\"hidden\" name=\"do\" value=\"changeperms\" />
	<input type=\"hidden\" name=\"album\" value=\"{$album}\" />
<table width=\"98%\" align=\"center\" cellpadding=\"1\" cellspacing=\"1\" border=\"0\">
<tr><th colspan=\"2\">Buddies</th></tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:confirm_delete:desc::trigger:>
//===========================================================================
function confirm_delete($album="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"borderwrapm\">
<div class=\"maintitle\">{ipb.lang['delete']}</div>
<div class='formsubtitle'><center>{ipb.lang['del_confirm']}
<br /><br /><a href='{ipb.script_url}&act=module&module=gallery&cmd=albums&op=del&album={$album}&confirm_delete=true'>{ipb.lang['del_conf_link']}</a>
</center></div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:error:desc::trigger:>
//===========================================================================
function error($type="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"formsubtitle\">{ipb.lang[$type.'_title']}</div>
<p>{ipb.lang[$type.'_text']}</p>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:form_errors:desc::trigger:>
//===========================================================================
function form_errors($text="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"errorwrap\">
	<h4>{ipb.lang['errors_found']}</h4>
	{$text}
</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:index_end:desc::trigger:>
//===========================================================================
function index_end() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "" . (($this->ipsclass->vars['gallery_album_create']==1) ? ("
<tr>
			<td class=\"formbuttonrow\" align=\"center\" colspan=\"6\"><b><a href=\"{ipb.script_url}automodule=gallery&cmd=albums&op=addnew\">{ipb.lang['create_album']}</a></b></td>
		</tr>
") : ("
  <tr></tr>
")) . "

	</table>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:index_row:desc::trigger:>
//===========================================================================
function index_row($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
			<td class=\"row1\"><b>{$data['name']}</b><br /><i>{$data['description']}</i>

</td>
			<td class=\"row1\" align=\"left\"><i>{$data['status']}</i></td>
			<td class=\"row1\" align=\"center\"><i>{$data['in_category']}</i></td>
			<td class=\"row2\" align=\"center\">{$data['comments']}</td>
			<td class=\"row2\" align=\"center\">{$data['images']}</td> 
			<td class=\"row2\" align=\"center\">{$data['controls']}</td>
		</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:index_top:desc::trigger:>
//===========================================================================
function index_top() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<script language=\"javascript\">
	<!--
function do_op( obj )
{
     goto_url= obj.options[obj.selectedIndex].value;
     locationjump( goto_url );
}
	-->
</script>
	<div class=\"formsubtitle\">{ipb.lang['album_manage']}</div>
	<table cellspacing=\"1\" width=\"100%\">
		<tr>
			<th width=\"35%\">{ipb.lang['album_info']}</th>
			<th width=\"5%\"  align=\"center\">{ipb.lang['album_status']}</th>
			<th width=\"15%\" align=\"center\">{ipb.lang['cat_name']}</th>
			<th width=\"10%\" align=\"center\">{ipb.lang['comments']}</th>
			<th width=\"10%\" align=\"center\">{ipb.lang['images']}</th>
			<th width=\"25%\" align=\"center\">{ipb.lang['album_controls']}</th>
		</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:no_albums:desc::trigger:>
//===========================================================================
function no_albums() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"formsubtitle\">{ipb.lang['no_album']}</div>
<p><a href=\"{ipb.script_url}automodule=gallery&cmd=albums&op=addnew\">{ipb.lang['first_album']}</a></p>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:perms_finished:desc::trigger:>
//===========================================================================
function perms_finished() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<table class=\"ipbtable\" width=\"98%\" align=\"center\" cellpadding=\"1\" cellspacing=\"0\" border=\"0\">
<tr><td>{ipb.lang['gallery_perms_done']}</td></tr>
</table>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:upload_form_top:desc::trigger:>
//===========================================================================
function upload_form_top($errors="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<script language=\"Javascript\" type=\"text/javascript\">
	<!--
		function PopUp(url, name, width,height,center,resize,scroll,posleft,postop){
			if (posleft != 0){ x = posleft }
			if (postop  != 0){ y = postop  }
	
			if (!scroll){ scroll = 1 }
			if (!resize){ resize = 1 }
	
			if ((parseInt (navigator.appVersion) >= 4 ) && (center)){
				X = (screen.width  - width ) / 2;
				Y = (screen.height - height) / 2;
			}
			if (scroll != 0){ scroll = 1 }
	
			var Win = window.open( url, name, 'width='+width+',height='+height+',top='+Y+',left='+X+',resizable='+resize+',scrollbars='+scroll+',location=no,directories=no,status=no,menubar=no,toolbar=no');
		}
	//-->
</script>
<div class=\"formsubtitle\">{ipb.lang['submit_post']}</div>
{$errors}
<form method=\"post\" action=\"{ipb.script_url}\" name=\"REPLIER\" enctype=\"multipart/form-data\">
	<input type=\"hidden\" name=\"act\" value=\"module\" />
	<input type=\"hidden\" name=\"module\" value=\"gallery\" />
	<input type=\"hidden\" name=\"cmd\" value=\"albums\" />
	<input type=\"hidden\" name=\"op\"  value=\"do_upload\" />
	<input type=\"hidden\" name=\"album\" value=\"{ipb.input['album']}\" />
	<table cellspacing=\"1\" width=\"100%\">";
//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>

</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>