<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 3                     */
/* CACHE FILE: Generated: Thu, 24 May 2007 13:16:02 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_gallery_user_3 {

 var $ipsclass;
//===========================================================================
// <ips:forum_filter:desc::trigger:>
//===========================================================================
function forum_filter($options="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<form action=\"{ipb.script_url}\" method=\"post\" name=\"jumpmenu\">
	<input type=\"hidden\" name=\"automodule\" value=\"gallery\" />
	<input type=\"hidden\" name=\"cmd\" value=\"user\" />
	<input type=\"hidden\" name=\"user\" value=\"{ipb.input['user']}\" />
	<input type=\"hidden\" name=\"op\" value=\"ipbimages\" />
	<input type=\"hidden\" name=\"s\" value=\"{ipb.session_id}\" />
	<p>{ipb.lang['filter_forum']}
	<select name=\"f\">
		<option value=\"\">{ipb.lang['no_forum_filter']}</option>
		{$options}
	</select>&nbsp;
	<input type=\"submit\" value=\"{ipb.lang['jmp_go']}\" /></p>
</form>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:img_view_end:desc::trigger:>
//===========================================================================
function img_view_end($span="",$info="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr> 
			<td class=\"formbuttonrow\" colspan=\"{$span}\" align=\"center\">&nbsp;{ipb.lang['showing']}</td>
		</tr>
		
	</table>
</div>
<table cellspacing=\"1\" width=\"100%\" align=\"left\">
		<tr>
			<td nowrap=\"nowrap\">{$info}</td>
		</tr>
	</table>
<script type=\"text/javascript\" src='jscripts/ipb_galleryjs.js'></script>
<script type='text/javascript'>
//<![CDATA[
// Resize thumb divs...
var use_thumbs = parseInt(\"{ipb.vars['gallery_create_thumbs']}\");
var thumbs_x   = parseInt(\"{ipb.vars['gallery_thumb_width']}\");
var thumbs_y   = parseInt(\"{ipb.vars['gallery_thumb_height']}\");
html_resize_thumb_divs( use_thumbs, thumbs_x, thumbs_y );
//]]>
</script>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:img_view_top:desc::trigger:>
//===========================================================================
function img_view_top($info="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"subtitle\">{$info['where']}</div>
<div class=\"formsubtitle\" style=\"text-align:left;\">{$info['description']}</div>
    <table cellspacing=\"1\" class=\"ipbtable\" width=\"100%\">
		<tr>
			<td nowrap=\"nowrap\">{$info['SHOW_PAGES']}</td>
		</tr>
	</table>
	<table cellspacing=\"1\" width=\"100%\">
	<tr><td align=\"right\" colspan=\"3\">{$info['upload']}&nbsp;{$info['multi_upload_button']}&nbsp;{$info['slideshow']}&nbsp;</td></tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:page_end:desc::trigger:>
//===========================================================================
function page_end() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "</td></tr></table>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:user_bar:desc::trigger:>
//===========================================================================
function user_bar($info="",$base_url='') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<table cellspacing=\"0\" class=\"ipbtable\" width=\"100%\">
	<tr>
		<td class=\"nopad\" valign=\"top\" width=\"24%\">
		
                          <div class=\"borderwrap\">
				<div class=\"maintitle\">{ipb.lang['user_info']}</div>
                         
				<div class=\"formsubtitle\">{ipb.lang['user_stats']}</div>
				<p>
					&middot; <b>{ipb.lang['total_imgs']}</b> {$info['total_images']}<br />
					&middot; <b>{ipb.lang['total_comments']}</b> {$info['total_comments']}<br />
					&middot; <b>{ipb.lang['dp_used']}</b> {$info['total_diskspace']}<br /> <i><!-- TOTAL_ALLOWED --></i>
					{$info['pub_albums']}
				</p>
				<!-- PRIVATE_ALBUMS -->
				<!-- CONTROLS -->
		</div>
		
		</td>
		<td width=\"1%\" class=\"nopad\">&nbsp;</td>
		<td class=\"nopad\" valign=\"top\" width=\"75%\">
	
   <div class=\"borderwrap\">
			<div class=\"maintitle\">{$info['name']}</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:user_bar_footer:desc::trigger:>
//===========================================================================
function user_bar_footer() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "</p>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:user_bar_header:desc::trigger:>
//===========================================================================
function user_bar_header($text='') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"formsubtitle\">{$text}</div>
<p>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:user_bar_public_albums:desc::trigger:>
//===========================================================================
function user_bar_public_albums($albums="",$mid="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "</p>
<div class=\"formsubtitle\">{ipb.lang['user_pub_albums']}</div>
<p>
	&middot; <a href=\"{ipb.script_url}automodule=gallery&cmd=user&user={$mid}&op=ipbimages\"><b>{ipb.lang['where_all_ipb']}</b></a><br />
	{$albums}";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:user_bar_row:desc::trigger:>
//===========================================================================
function user_bar_row($text="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "&middot; {$text} <br />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:user_view_top:desc::trigger:>
//===========================================================================
function user_view_top($info='') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"subtitle\">{ipb.lang['album_all']}</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:user_view_top_cat:desc::trigger:>
//===========================================================================
function user_view_top_cat($info='') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"subtitle\">{ipb.lang['where_all']}</div>
   
 <table cellspacing=\"1\" class=\"ipbtable\" width=\"100%\">
		<tr>
			<td nowrap=\"nowrap\" width=\"75%\">{$info['SHOW_PAGES']}</td>
			<td align=\"right\" colspan=\"3\">{$info['upload']}&nbsp;{$info['slideshow']}</td>
		</tr>
	</table>
	<table cellspacing=\"1\" width=\"100%\">";
//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>

</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>