<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 3                     */
/* CACHE FILE: Generated: Thu, 24 May 2007 13:16:02 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_gallery_search_3 {

 var $ipsclass;
//===========================================================================
// <ips:no_results:desc::trigger:>
//===========================================================================
function no_results() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"borderwrap\">
<div class=\"maintitle\"><{CAT_IMG}> {ipb.lang['search_results']}</div>
<table width=\"100%\" class=\"ipbtable\" cellpadding=\"2\">
<tr><td class=\"row1\" align=\"center\">{ipb.lang['no_results']}</td></tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:search_end:desc::trigger:>
//===========================================================================
function search_end() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "</table></div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:search_row:desc::trigger:>
//===========================================================================
function search_row($info="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr><td class=\"row1\" align=\"center\">
       <table width=\"100%\">
         <tr><td align=\"center\">{$info['image']}</td>
             <td valign=\"top\" width=\"70%\"><i>{$info['stuff']}<br />
             {ipb.lang[ 'postedby' ]} {$info['user']}
             </td></tr>
       </table></td>
</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:search_top:desc::trigger:>
//===========================================================================
function search_top() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"borderwrap\">
<div class=\"maintitle\"><{CAT_IMG}> {ipb.lang['search_results']}</div>
<table width=\"100%\" class=\"ipbtable\" cellpadding=\"2\">
<tr>
  <th width=\"100%\">&nbsp;</th>
</tr>";
//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>

</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>