<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 3                     */
/* CACHE FILE: Generated: Thu, 24 May 2007 13:16:02 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_gallery_post_3 {

 var $ipsclass;
//===========================================================================
// <ips:edit_form_top:desc::trigger:>
//===========================================================================
function edit_form_top($data="",$cat="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<script type=\"text/javascript\" src=\"jscripts/ipb_editor.js\"></script>
<script type=\"text/javascript\" src=\"jscripts/ipb_editor_std.js\"></script>

<form method=\"post\" id='postingform' action=\"?automodule=gallery\" name=\"REPLIER\" enctype=\"multipart/form-data\" onsubmit='return ValidateForm()'>
	<input type=\"hidden\" name=\"cmd\" value=\"editimg\" />
	<input type=\"hidden\" name=\"op\" value=\"doedit\" />
	<input type=\"hidden\" name=\"cat\" value=\"{$cat}\"  />
	<input type=\"hidden\" name=\"img\" value=\"{ipb.input['img']}\" />
	<div class=\"borderwrap\">
	<table cellspacing=\"0\" width=\"100%\" class='ipbtable'>
		<tr>
			<td class=\"maintitle\" colspan=\"2\"><{CAT_IMG}>&nbsp;{ipb.lang[$data]}</td>
		</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:edit_reply_form_top:desc::trigger:>
//===========================================================================
function edit_reply_form_top($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<form method=\"post\" action=\"{ipb.script_url}\" name=\"REPLIER\" enctype=\"multipart/form-data\" onsubmit='return ValidateForm()'>
	<input type=\"hidden\" name=\"automodule\" value=\"gallery\" />
	<input type=\"hidden\" name=\"cmd\" value=\"editcomment\" />
	<input type=\"hidden\" name=\"op\"  value=\"doeditcomment\" />
	<input type=\"hidden\" name=\"img\" value=\"{ipb.input['img']}\" />
	<input type=\"hidden\" name=\"comment\" value=\"{ipb.input['comment']}\" />
	<div class=\"borderwrap\">
	<table cellspacing=\"0\" width=\"100%\"  class=\"ipbtable\">
		<tr>
			<td class=\"maintitle\" colspan=\"2\"><{CAT_IMG}>&nbsp;{ipb.lang[$data]}</td>
		</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:get_append_chk:desc::trigger:>
//===========================================================================
function get_append_chk($checked='') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<input type=\"checkbox\" name=\"add_edit\" class=\"checkbox\" value=\"1\" $checked />&nbsp;{ipb.lang['append_edit']}<br />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:get_post_options:desc::trigger:>
//===========================================================================
function get_post_options($emo="",$sig="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
        <td colspan=\"2\" align=\"center\" class=\"bgl\">
         <div style=\"width:100%;\" align=\"center\" class=\"borderwrap\">
         <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"darkrow3\">
    		<tr>
				<td align=\"right\" width=\"20%\" valign='top'><strong>{ipb.lang['po_options']}</strong></td>
				<td align=\"left\" width=\"80%\">
				 <input type=\"checkbox\" name=\"enableemo\" class=\"checkbox\" value=\"yes\" $emo />&nbsp;{ipb.lang['enable_emo']}<br />
				 <input type=\"checkbox\" name=\"enablesig\" class=\"checkbox\" value=\"yes\" $sig />&nbsp;{ipb.lang['enable_sig']}
				 <!-- APPEND_EDIT -->
				</td>
			</tr>
     	</table>
     	</div>
     	</td>
	</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:move_form_top:desc::trigger:>
//===========================================================================
function move_form_top($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<form method=\"post\" action=\"{ipb.script_url}\" name=\"REPLIER\" enctype=\"multipart/form-data\">
	<input type=\"hidden\" name=\"automodule\" value=\"gallery\" />
	<input type=\"hidden\" name=\"cmd\" value=\"moveimg\" />
	<input type=\"hidden\" name=\"op\" value=\"domove\" />
	<input type=\"hidden\" name=\"img\" value=\"{ipb.input['img']}\" />
	<div class=\"borderwrap\">
	<table cellspacing=\"1\" cellpadding=\"5\" width=\"100%\">
		<tr>
			<td class=\"maintitle\" colspan=\"2\"><{CAT_IMG}>&nbsp;{ipb.lang[$data]}</td>
		</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:post_control_drop:desc::trigger:>
//===========================================================================
function post_control_drop($name="",$options="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<select name=\"$name\">$options</select>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:post_control_file:desc::trigger:>
//===========================================================================
function post_control_file($name="",$value="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<input type=\"file\" name=\"{$name}\" value=\"{$value}\" size=\"71\" />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:post_control_textarea:desc::trigger:>
//===========================================================================
function post_control_textarea($name="",$value="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<textarea name=\"{$name}\" cols=\"57\" rows=\"6\">{$value}</textarea>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:post_control_textbox:desc::trigger:>
//===========================================================================
function post_control_textbox($name="",$value="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<input type=\"text\" name=\"{$name}\" value=\"{$value}\" size=\"60\" />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:post_description_field:desc::trigger:>
//===========================================================================
function post_description_field($editor_html='',$value='') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
        <td colspan=\"2\" align=\"center\" class=\"bgl\">
         <div style=\"width:100%;\" align=\"center\" class=\"borderwrap\">
         <table cellpadding=\"5\" cellspacing=\"5\" width=\"100%\" class=\"darkrow3\">
             <tr>
			<td align=\"right\" valign=\"top\" width=\"20%\">
				<!--SMILIE TABLE-->
			</td>
			<td align=\"left\" valign=\"top\" width=\"80%\">
                {$editor_html}
            </td></tr>
   </table></div>
</td></tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:post_form_end:desc::trigger:>
//===========================================================================
function post_form_end($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
			<td class=\"formbuttonrow\" colspan=\"2\">
				<input type=\"submit\" name=\"submit\" value=\"{ipb.lang[$data]}\" tabindex=\"4\" class=\"button\" accesskey=\"s\" />
			</td>
		</tr>
	</table>
	</div>
</form><br />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:post_form_row:desc::trigger:>
//===========================================================================
function post_form_row($title="",$control="",$desc="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
        <td colspan=\"2\" align=\"center\" class=\"bgl\">
         <div style=\"width:100%;\" align=\"center\" class=\"borderwrap\">
         <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"darkrow3\">
    		<tr>
				<td align=\"right\" width=\"20%\">{$title}<br />{$desc}</td>
				<td align=\"left\" width=\"80%\">{$control}</td>
			</tr>
     	</table>
     	</div>
     	</td>
	</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:post_form_sep:desc::trigger:>
//===========================================================================
function post_form_sep($title="",$desc="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
        <td colspan=\"2\" align=\"center\" class=\"bgl\">
         <div style=\"width:100%;\" align=\"center\" class=\"borderwrap\">
         <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"darkrow1\">
    		<tr>
				<tr>
				<td colspan=\"2\" width=\"100%\">
				<b>{$title}</b><br /><small>{$desc}</small>
			</td>
			</tr>
     	</table>
     	</div>
     	</td>
	</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:post_form_top:desc::trigger:>
//===========================================================================
function post_form_top($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<form method=\"post\" id='postingform' action=\"{ipb.script_url}\" name=\"REPLIER\" enctype=\"multipart/form-data\" onsubmit='return ValidateForm()'>
    <input type=\"hidden\" name=\"automodule\" value=\"gallery\" />
	<input type=\"hidden\" name=\"cmd\" value=\"dopost\" />
	<input type=\"hidden\" name=\"cat\" value=\"{ipb.input['cat']}\" />
	<input type=\"hidden\" name=\"album\" value=\"{ipb.input['album']}\" />

	<div class=\"borderwrap\">
	<table cellspacing=\"0\" width=\"100%\" class=\"ipbtable\">
		<tr>
			<td class=\"maintitle\" colspan=\"2\"><{CAT_IMG}>&nbsp;{ipb.lang[$data]}</td>
		</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:post_javascript:desc::trigger:>
//===========================================================================
function post_javascript() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<!--nothing-->";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:reply_form_top:desc::trigger:>
//===========================================================================
function reply_form_top($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<form method=\"post\" action=\"{ipb.script_url}\" name=\"REPLIER\" enctype=\"multipart/form-data\" onsubmit='return ValidateForm()'>
	<input type=\"hidden\" name=\"automodule\" value=\"gallery\" />
	<input type=\"hidden\" name=\"cmd\" value=\"postcomment\" />
	<input type=\"hidden\" name=\"op\"  value=\"doaddcomment\" />
	<input type=\"hidden\" name=\"img\" value=\"{ipb.input['img']}\" />
	<div class=\"borderwrap\">
	<table cellspacing=\"0\" width=\"100%\"  class=\"ipbtable\">
		<tr>
			<td class=\"maintitle\" colspan=\"2\"><{CAT_IMG}>&nbsp;{ipb.lang[$data]}</td>
		</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:smilie_table:desc::trigger:>
//===========================================================================
function smilie_table() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<!--THE SMILIES-->";
//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>

</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>