<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 3                     */
/* CACHE FILE: Generated: Thu, 24 May 2007 13:16:02 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_gallery_portal_3 {

 var $ipsclass;
//===========================================================================
// <ips:tmpl_random_image_wrap:desc::trigger:>
//===========================================================================
function tmpl_random_image_wrap($image="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<br />
<div class=\"borderwrap\">
	<div class=\"maintitle\"><{CAT_IMG}>&nbsp;{ipb.lang['gallery_random']}</div>
	<div class='tablepad' align='center'>{$image}</div>
</div>";
//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>

</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>