<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 3                     */
/* CACHE FILE: Generated: Thu, 24 May 2007 13:16:02 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_gallery_imagelisting_3 {

 var $ipsclass;
//===========================================================================
// <ips:basic_row:desc::trigger:>
//===========================================================================
function basic_row($msg="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
	<td class=\"row1\" align=\"center\">
		<b>{ipb.lang[$msg]}</b>
	</td>
</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:container_row_bottom:desc::trigger:>
//===========================================================================
function container_row_bottom() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "</table>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:container_row_top:desc::trigger:>
//===========================================================================
function container_row_top() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<table cellspacing=\"1\" width=\"100%\">";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:image_info_line:desc::trigger:>
//===========================================================================
function image_info_line($title="",$text="",$alt='') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<p {$alt}><b>$title</b> $text</p>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:rate_form:desc::trigger:>
//===========================================================================
function rate_form($img='') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div align='center' style='height:25px'>
 <span style=\"cursor: pointer;\" class=\"fauxbutton\" id=\"rate_image_{$img}\"><a href=\"#rate_image_{$img}\">{ipb.lang['rate_image']}&nbsp;<img src=\"{ipb.vars['img_url']}/menu_action_down.gif\" alt=\"V\" title=\"Open Menu\" border=\"0\"></a></span>
</div>
<script type=\"text/javascript\">
 menu_build_menu( \"rate_image_{$img}\",
  new Array( \"<div style='width:150px;padding:6px;'><form action='{ipb.script_url}&automodule=gallery&cmd=rate' method='POST'>\"
  			+'<input type=\"hidden\" name=\"img\" value=\"{$img}\" />'
  			+'<input type=\"hidden\" name=\"cat\" value=\"{ipb.input['cat']}\" />'
			+'<input type=\"hidden\" name=\"album\" value=\"{ipb.input['album']}\" />'
			+'<input type=\"hidden\" name=\"op\" value=\"dorate\" />'
			+'<input type=\"hidden\" name=\"st\" value=\"{ipb.input['st']}\" />'
   			+'<input type=\"radio\" name=\"rating\" id=\"r5_{$img}\" value=\"5\"> &nbsp; <label for=\"r5_{$img}\"><img src=\"{ipb.vars['img_url']}/rating_5.gif\" border=\"0\" alt=\"XXXXX\" /></label><br />'
   			+'<input type=\"radio\" name=\"rating\" id=\"r4_{$img}\" value=\"4\"> &nbsp; <label for=\"r4_{$img}\"><img src=\"{ipb.vars['img_url']}/rating_4.gif\" border=\"0\" alt=\"XXXX\" /></label><br />'
   			+'<input type=\"radio\" name=\"rating\" id=\"r3_{$img}\" value=\"3\"> &nbsp; <label for=\"r3_{$img}\"><img src=\"{ipb.vars['img_url']}/rating_3.gif\" border=\"0\" alt=\"XXX\" /></label><br />'
   			+'<input type=\"radio\" name=\"rating\" id=\"r2_{$img}\" value=\"2\"> &nbsp; <label for=\"r2_{$img}\"><img src=\"{ipb.vars['img_url']}/rating_2.gif\" border=\"0\" alt=\"XX\" /></label><br />'
   			+'<input type=\"radio\" name=\"rating\" id=\"r1_{$img}\" value=\"1\"> &nbsp; <label for=\"r1_{$img}\"><img src=\"{ipb.vars['img_url']}/rating_1.gif\" border=\"0\" alt=\"X\" /></label><br />'
   			+\"<div align='center'><input type='submit' value=' {ipb.lang['rateit']} ' /></div>\"
   			+\"</form></div>\"
		    ) );
</script>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:view_album_row:desc::trigger:>
//===========================================================================
function view_album_row($info='') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<td align=\"center\" class=\"nopad\" valign=\"top\" width='50%'>
   <div class=\"thumbwrap\">   
   	<div class=\"popupmenu\">
   	  <table width=\"100%\" cellpadding=\"3\" border=\"0\">
       <tr><td width=\"50%\"><b>{ipb.lang['albums']}: <a href='{ipb.script_url}automodule=gallery&cmd=user&user={$info['member_id']}&op=view_album&album={$info['id']}'>{$info['name']}</a></b><br />
        <p class='alt'><b>{ipb.lang['images']}: </b>{$info['images']}</p>
        <p><b>Date: </b>{$info['date']}</p></td>
        <td width=\"50%\">{$info['image']}</td></tr>
       </table>
    </div>
    </div>
</td>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:view_begin_row:desc::trigger:>
//===========================================================================
function view_begin_row() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:view_cat_row:desc::trigger:>
//===========================================================================
function view_cat_row($info='') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<td align=\"center\" class=\"nopad\" valign=\"top\" width='50%'>
		<div class=\"thumbwrap\">
<h4>{ipb.lang['cat_name']}: <a href='{ipb.script_url}act=module&module=gallery&cmd=user&user={ipb.input['user']}&op=view_cat&cat={$info['catid']}'>{$info['name']}</a></h4>
{$info['image']}
<p><b>Date: </b>{$info['date']}
		</div> 
	</td>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:view_end_row:desc::trigger:>
//===========================================================================
function view_end_row() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:view_row_img:desc::trigger:>
//===========================================================================
function view_row_img($info="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<td align=\"center\" class=\"nopad\" valign=\"top\">
		<div class=\"thumbwrap\">
			<h4>{$info['caption']}</h4>
			<div class=\"thumb\">{$info['image']}</div>
			{$info['info']}
			<p><b>{$info['extra']}</b></p>
		</div> 
	</td>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:view_row_img_hidden:desc::trigger:>
//===========================================================================
function view_row_img_hidden($info="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<td align=\"center\" class=\"nopad\" valign=\"top\">
		<div class=\"thumbwrap\">
			<h4>{$info['caption']}</h4>
			<div class=\"thumb\">{$info['image']}</div>
{$info['info']}
			<p><b>{$info['extra']} {ipb.lang['not_approved']}</b></p>
		</div>
	</td>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:view_row_img_pinned:desc::trigger:>
//===========================================================================
function view_row_img_pinned($info="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<td align=\"center\" class=\"nopad\" valign=\"top\">
		<div class=\"thumbwrapp\">
			<h4>{$info['caption']}</h4>
			<div class=\"thumb\">{$info['image']}</div>
{$info['info']}
			<p class=\"pin\">{$info['extra']} <b>{ipb.lang['pinned']}</b></p>
		</div>
	</td>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:view_row_ipb:desc::trigger:>
//===========================================================================
function view_row_ipb($info="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<td align=\"center\" class=\"nopad\" valign=\"top\">
		<div class=\"thumbwrap\">
			<div class=\"thumb\">{$info['image']}</div>
			<p><b>{ipb.lang['uploaded_by']}</b> {$info['name']}</p>
			<p class=\"alt\"><b>{ipb.lang['on']}</b> {$info['date']}</p>
		</div> 
	</td>";
//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>

</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>